### ISSUE TITLE
Unable to open their inventory

### ISSUE THREAD

**Issue by JordanKef** [seymourimadeit/guardvillagers#108]
I can give them the sword or the crossbow to turn them into guards them but nothing else. i cannot open their inventory. i tried in creative mode, i had "hero of the village" as well but nothing, no inventory. I play this mod on 1.16 from the modpack "Better Minecraft"

**Comment by seymourimadeit** [comment]
We don't support 1.16 anymore and you can only get into the guards inventory with hero of the village in that version, not also by converting a villager into a guard.
