### ISSUE TITLE
new type of guard

### ISSUE THREAD

**Issue by carnivorchild** [seymourimadeit/guardvillagers#11]
would it be possible to convert some other kind of humanoid entity into guard like the skeleton, wither skeleton, the's different type of zombies as well as illagers and piglins?
-the living dead will have to be resuscitated thanks to the resurrection altar but if the resurection fails the living dead will be aggressive and will attack the player
-the piglins and illagers will be recruited on contract.
contracts have different levels and will be made with ink paper and a different amount of gold or emerald.
if the contract does not please the illagers or piglins they will be angry and they will attack the player

**Comment by seymourimadeit** [comment]
Read the pinned post.

**Comment by carnivorchild** [comment]
I just posted my suggestion in the right place, sorry I don't often use github
