### ISSUE TITLE
[1.19.2] Other villagers are obsessed with the guards.

### ISSUE THREAD

**Issue by Neposis** [seymourimadeit/guardvillagers#110]
Heya,
I have found that Villagers form these huge hoards and follow the guards around during their conversation time, even into their work time and just not stop. They will even fall off cliffs.

I am not sure if this is the intended behaviour but it is really annoying and causes the villagers to go crazy.
I've seen them dancing, spinning, vibrating their heads and all sorts.

Regards

**Comment by seymourimadeit** [comment]
Fixed in dev.

**Comment by Neposis** [comment]
Ah cheers, good to know. Glad you're so active on the mod!
