### ISSUE TITLE
[1.19.2] Still cannot open guards' inventories

### ISSUE THREAD

**Issue by Kaligraphy22** [seymourimadeit/guardvillagers#117]
Forge 1.19.2-43.2.0
guardvillagers-1.19.2-1.5.5

Saw Issue seymourimadeit/guardvillager-suggestions#109 but I am still unable to open the guards' inventories. Every villager in my village is Master and I've not hit anyone. The villagers gossip every day and my further proof are all the discounted prices I get. I do not have Hero of the Village but the info on the Curseforge page implies that that is but one of three ways to get into their inventories.

Form the Curseforge page:
"Guards can 'gossip' with villagers and will trust the player to open their inventory if **they have a high enough reputation,** **have hero of the village**, or is **created by the player**."

So is it that I just need Hero of the Village? Nothing else?

**Comment by seymourimadeit** [comment]
Are the guards in the same room as the villagers and thus have a chance to be near them? Keep in mind that the reputation feature takes time to build up when gossiping.

**Comment by Kaligraphy22** [comment]
They haven't been confined to a room together but they frequently patrol through the village center around the time the villagers start gossiping. I thought the reputation would be faster considering I traded so much and get discounts here and there. Should I try to confine them a house with a villager to speed things along or should I just be more patient?

**Comment by seymourimadeit** [comment]
Try confining each of them into a room to speed things up. I'll be closing this for now unless the problem persists.
