### ISSUE TITLE
Wont work

### ISSUE THREAD

**Issue by ezioblade121** [seymourimadeit/guardvillagers#12]
I downloaded the mod and when I goto my forge silent on Minecraft it says it installed but when I try to make villagers into guards it won't work

**Comment by seymourimadeit** [comment]
please give us more detail, being vague wont help us at all, for example elaborate on "doesnt work"

**Comment by ezioblade121** [comment]
Im sorry I downloaded the mod and did a the right steps it when I uploaded
my 1.15.2 client it said 3 mods weird downloaded but when i go start up my
world it seems that the mod hasn't changed anything it its not working. ( I
cant make guards and they are not spawning in)

**Comment by seymourimadeit** [comment]
have you tried shift right clicking on a villager with a sword to make a guard? and have you tried spawning a guard via spawn eggs?

**Comment by ezioblade121** [comment]
Alrighty let me try

**Comment by Minecraftiscool987** [comment]
Hey I dragged the file on my resource packs and it always says "Failed to copy"
Any suggestions?

**Comment by seymourimadeit** [comment]
> Hey I dragged the file on my resource packs and it always says "Failed to copy"
> Any suggestions?
> Also what version do I need to launch this mod on?

first off, dont hijack threads, 2nd of, this isnt a resource pack, this is a mod, there are various tutorials around the internet that show you how to download forge mods.

**Comment by Minecraftiscool987** [comment]
> > Hey I dragged the file on my resource packs and it always says "Failed to copy"
> > Any suggestions?
> > Also what version do I need to launch this mod on?
> 
> first off, dont hijack threads, 2nd off, this isnt a resource pack, this is a mod, there are various tutorials around the internet that show you how to download forge mods. the jar file clearly states the version this mod is for.

Thanks.
