### ISSUE TITLE
error-1.18.2-server

### ISSUE THREAD

**Issue by lodest-game** [seymourimadeit/guardvillagers#120]
forge-1.18.2-40.2.4
 [minecraft/LootTables]: Couldn't parse loot table guardvillagers:entities/guard_helmet
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'minecraft:gold_helmet'

**Comment by seymourimadeit** [comment]
this problem is caused by the fact that you miswrote minecraft:golden_helmet as gold_helmet.

**Comment by lodest-game** [comment]
thanks，so,what should I do?I'm a Novice，and my en is so bad

**Comment by seymourimadeit** [comment]
i recommend you use this site for generating the guard loot tables, though it may require some tinkering 

https://misode.github.io/loot-table/

**Comment by lodest-game** [comment]
thanks,I will be trying
