### ISSUE TITLE
Issues with villager animations.

### ISSUE THREAD

**Issue by Anewri32** [seymourimadeit/guardvillagers#121]
I have been using this mod for a while and I have always had problems with the animations of the villagers, more specifically their heads, and it is that they do not rotate. When removing the mod miraculously the villagers returned to normal, so I went back to a previous version of the mod, more specifically to 1.5.1 and I didn't have any problems.

This error happens in version 1.19.2 of minecraft, with version 1.5.5 of the mod, Forge: 43.2.11

As it is an animation problem, I don't have an image or a log to show.

**Comment by seymourimadeit** [comment]
fixed in dev
