### ISSUE TITLE
this mod 1.16.5 version not working with aternos server

### ISSUE THREAD

**Issue by yqminecraftplayer** [seymourimadeit/guardvillagers#122]
I am using guard villager 1.16.5 version last week ago with Tlauncher.Today when I activate,the aternos minecraft server,it kick me instantly and its reason is [23:39:53] [Netty Epoll Server IO #2/ERROR] [ne.mi.fm.ne.NetworkRegistry/NETREGISTRY]: Channels [guardvillagers:main] rejected their client side version number
[23:39:53] [Netty Epoll Server IO #2/ERROR] [ne.mi.fm.ne.FMLHandshakeHandler/FMLHANDSHAKE]: Terminating connection with client, mismatched mod list.This is the log:https://mclo.gs/nPNQLnp

**Comment by seymourimadeit** [comment]
We won't provide support for pirated launchers like TLauncher.
