### ISSUE TITLE
[1.20.1] Guard Villagers still attacks snow golems and with the melon golem mod

### ISSUE THREAD

**Issue by donkinbois** [seymourimadeit/guardvillagers#123]
![Screen Shot 2023-07-08 at 5 14 00 PM](https://github.com/seymourimadeit/guardvillagers/assets/104707112/e3982529-8c4d-42c2-95e8-d0725e0eeaf9)

Forge: 47.0.46
guard villagers 1.20-1.6.0

basically when snow golem or melon golem attacks the guard, the guard fights then back # #

**Comment by seymourimadeit** [comment]
Addressed in dev.
