### ISSUE TITLE
Crash problem

### ISSUE THREAD

**Issue by V-de-Vito** [seymourimadeit/guardvillagers#127]
Good morning,
First of all thank you for this great mod, I use it since 1.16.5 and I love it.
However, I just installed it on my server yesterday and when I want to equip a guard or make it stagnate on a position, the server crashes and gives me this error in the console.

I do not understand where the problem can come from and I have no experience in the field, maybe someone else has already encountered this problem but I did not find any information on it.

If you could let me know where the problem is coming from, I would greatly appreciate it.

Thank you for taking the time to read me.
Cordially

![Capture d’écran 2023-08-02 212108](https://github.com/seymourimadeit/guardvillagers/assets/136616082/6265eb6c-72b6-4139-91d7-a32d610f5f34)

**Comment by seymourimadeit** [comment]
Firstly, you're welcome I really appreciate those comments. 

This issue seems to primarily come from bukkit. Bukkit is inherently compatible with forge, so no way for me to provide support for this. I suggest you try to find a more forge compatible version of bukkit or drop it altogether.

**Comment by V-de-Vito** [comment]
Thank you for trying to help me. I will try not to use certain functionality of your mod while waiting to find another solution.
Thanks again and good luck for the future.
