### ISSUE TITLE
According to the Blame mod,  a guard loot table may have glitched

### ISSUE THREAD

**Issue by BugmanBugman** [seymourimadeit/guardvillagers#13]
https://gist.github.com/BugmanBugman/25d9218043800c27cbed881dc49fd7f6

**Comment by seymourimadeit** [comment]
Guards aren't even intended to have standard loot tables, the only thing they should drop are their inventory contents, so this isn't really a big deal, but I will add a empty guard loot table file to stop this error from popping up next morning.
