### ISSUE TITLE
Crossbow Guards cannot accurately hit enemies when firing fireworks

### ISSUE THREAD

**Issue by v191949v** [seymourimadeit/guardvillagers#130]
When crossbow guards fire fireworks, the projectile trajectory will always be offset upwards instead of being fired forward. This may be a problem in vanilla. Are you going to make crossbow guards fire fireworks correctly?

**Comment by seymourimadeit** [comment]
I think you should report this to mojang instead since this is an issue with all crossbow using mobs. I'll see if I can fix this for the guards but I'm gonna have to close this since this isn't a mod specific issue.
