### ISSUE TITLE
Crash, ThreadLocalRandom accessed from a different thread

### ISSUE THREAD

**Issue by Mikeatron-User** [seymourimadeit/guardvillagers#131]
# Information
**Forge Version:** 47.1.0
**Minecraft Version:** 1.20.1
**Modpack:** Sculk Horde Survival
**Modpack Version:** 1.0.5

# How to Recreate
1. Download Sculk Horde Survival 1.0.5
2. Load into world
3. Crash

# Crash Log
https://gist.github.com/Mikeatron-User/4effeea76ec4a1db2a74366d8846689a

**Comment by seymourimadeit** [comment]
For now I'd suggest turning on the fatal warning option in the ThreadLocalRandom detection mod until this is properly resolved.
