### ISSUE TITLE
Melee guards won't get close  to attacking range

### ISSUE THREAD

**Issue by AmberiumKoe** [seymourimadeit/guardvillagers#137]
i'm currently playing with "guardvillagers-1.16.5.1.2.6.jar" version of the mod, for a custom modpack i formed in forge. the archer villagers works as expected, they would run at the enemy and aggressively attack. However, the melee guards would simply hold a certain distant and not go near any opponents. making them vulnerable against range foes. they still attack any foes who would go near them. But they refuse to get closer themself. 

Is this intentional? or is it a bug?

**Comment by seymourimadeit** [comment]
We don't support 1.16.5 anymore and this feature (melee guards maintaining distance and backing uo while attacking) is intentional.
