### ISSUE TITLE
1.16, Guards not displaying armor

### ISSUE THREAD

**Issue by mettlephaontoms** [seymourimadeit/guardvillagers#14]
Ive been making spawn eggs that summon mobs already equipped with armors and weapons, and for some reason the guard villager does not display their armor when they are summoned from a spawn egg, they will drop it though. 
Guard villagers who are summoned from a custom spawn egg also do not pick up any armor, they will run to and stay where armor is dropped until it despawns.

![2020-08-02_05 50 54](https://user-images.githubusercontent.com/69108092/89121385-26cd9400-d484-11ea-918b-9c6456fc7e81.png)
![2020-08-02_05 43 53](https://user-images.githubusercontent.com/69108092/89121304-60ea6600-d483-11ea-9734-754f8e28b9f5.png)
![2020-08-02_05 44 05](https://user-images.githubusercontent.com/69108092/89121310-6942a100-d483-11ea-8a5d-5cbc94b177ae.png)

**Comment by seymourimadeit** [comment]
>CanPickUpLoot:0b

theres your problem with guards not picking up armor.

also, this command /give @p skeleton_spawn_egg{EntityTag:{id:"guardvillagers:guard",ArmorItems:[{},{id:"minecraft:chainmail_leggings",Count:1},{Count:1,id:"minecraft:elytra"},{id:"minecraft:iron_helmet",Count:1}],ArmorDropChances:[0F,0F,2F,0F]}} works and gives them armor when spawned in.

**Comment by abigailfails** [comment]
Is this still an issue, or should it be closed?

**Comment by abigailfails** [comment]
From what I can tell it's a vanilla problem.
