### ISSUE TITLE
Guard villagers can see/hit mobs through walls

### ISSUE THREAD

**Issue by minecraftedleen** [seymourimadeit/guardvillagers#140]
I put a bunch of illagers in a box and spawned guard villagers outside the box but the guards somehow saw and attacked them while the illagers couldn't fight back

**Comment by seymourimadeit** [comment]
Can't recreate on 1.20.2; if this is on 1.20.1 then I can't fix it considering that it's a universal problem for all mobs on past versions.

Closing for now.
