### ISSUE TITLE
Guards kill me no matter what, even after I die

### ISSUE THREAD

**Issue by Nocture1001** [seymourimadeit/guardvillagers#142]
So, I accidently rammed a villager with my boat from the Small Ships mod, and my Guard 100s of blocks away, in my base has become permanently hostile. Now, as I understand, that is normal as I heard they follow Iron Golem logic, however, the only time they stop being hostile is when I have the Hero of the Village effect, but the second I lose it, it's back to killing me. Even freshly spawned guards do the same. Even after I die, same thing! Iron Golems are not THIS prolific!

The only ones who don't immediately try to kill me are the Guards from a Village a few hundred blocks over. My base is located within the world's Spawn Chunks, so that may be the issue as well as my base currently not being a proper Village, just a boat with 3 beds and a few Villagers.

**Comment by seymourimadeit** [comment]
You can try either finding a way to raise your reputation amongst the villagers or lower the reputation needed to be angry at the player in the config.
