### ISSUE TITLE
Can't spawn villagers because game freezes and existing villagers disappear. Version 1.20.2 and version Forge 48.0.30

### ISSUE THREAD

**Issue by GreyWardenDane** [seymourimadeit/guardvillagers#144]
Well can't tell much, but could provide crashlog / savegame. Villagers can't be spawned with a spawnegg (if I try the game freezes) and if you get to close to a generated village the game crashes.

**Comment by GreyWardenDane** [comment]
Tried with only guard villagers, but still the same issue

**Comment by seymourimadeit** [comment]
Bug with forge, downgrade to 48.0.13.
