### ISSUE TITLE
Crash on 1.19.2-1.5.8

### ISSUE THREAD

**Issue by togera13** [seymourimadeit/guardvillagers#147]
I'm not exactly sure what is causing this, I removed a different mod that I thought was causing the conflict based on the crash report before this on, but the crash still happened & mentioned the guard villager again, so I am not sure what is happening.
[crash-2023-10-30_00.21.29-server.txt](https://github.com/seymourimadeit/guardvillagers/files/13200815/crash-2023-10-30_00.21.29-server.txt) Disabling guard villagers mod resolved the crash.

Also while I am at it, the health regen option doesn't seem to be working though I am using Minecraft Comes Alive in combination with this mod so idk if that had anything to do with it since I know that mod affected this one's villager health cap.

Also if you were to ever add more features to the mod I'd probably suggest adding a variant of the guard villager that uses ewewukek's musket mod's muskets, I've seen an illager mod that added illagers with muskets so I think it'd be fun to see a guard villager with one imo.

**Comment by seymourimadeit** [comment]
This seems more like a problem with the mutant creatures mod, try asking them about the issue.
