### ISSUE TITLE
Golem attacking player at night

### ISSUE THREAD

**Issue by OysterStew** [seymourimadeit/guardvillagers#148]
MC 1.20.1 
At night the Golems and sometimes the Guards turn on me and attack. I've got reputation set -9998 for golem and guards being aggroed. I've never attacked or hit a Guard, Golem or villager.

**Comment by seymourimadeit** [comment]
Does this bug occur with the mod alone or do you have any other mods on?

If it's the last one then try removing any mods that may affect mob ai one by one until the issue is resolved.

**Comment by OysterStew** [comment]
I'm using other mods. I'm using essentially the same mods I used in 1.19.2 without problem.  The attacks don't occur every night but for instance one golem chased me during the night then again during the next day. The others ignored me as did the guards. Something is triggering it. Is there a way to config so neither Guards nor Golems will never attack player?
 I"ll try a bare install with just Guard Villagers when I get a chance and get back to you.

**Comment by OysterStew** [comment]
[modlist.txt](https://github.com/seymourimadeit/guardvillagers/files/13259848/modlist.txt)

Mod List

**Comment by seymourimadeit** [comment]
>Is there a way to config so neither Guards nor Golems will never attack player?

Put minecraft:player in the blacklist in the config.

**Comment by seymourimadeit** [comment]
Also as an fyi the config for the reputation limit only affects guards, not golems.

**Comment by OysterStew** [comment]
Thank you

**Comment by OysterStew** [comment]
> > Is there a way to config so neither Guards nor Golems will never attack player?
> 
> Put minecraft:player in the blacklist in the config.

Still had a golem turn on me at night. Had to kill him as he cornered me. Other golem and guards seemed to ignore.


> Also as an fyi the config for the reputation limit only affects guards, not golems.

The config states golem _and_ guards in the description.

**Comment by seymourimadeit** [comment]
>The config states golem and guards in the description.

**Comment by seymourimadeit** [comment]
>The config states golem and guards in the description.

Then it's a wording mistake on my part.

>Still had a golem turn on me at night. 
Yeah I also misread this as only 'guards' and not 'guards and golems', the blacklist in the config only works for the guards not the golems. 

After a further analysis I don't think this is really a guard villager issue since this mod barely edits golem ai (it only makes the golems not attack guards), but if this issue appears in an instance with only guard villagers then I'll look into this more.
I'll be leaving this issue up for now.

**Comment by OysterStew** [comment]
10-4 thanks for looking into this for me. If I find the cause I'll let you know ...
