### ISSUE TITLE
Sou um novato. Onde posso colocar mobs na whitelist?

### ISSUE THREAD

**Issue by Mesaya1** [seymourimadeit/guardvillagers#149]
Desculpe por essa pergunta boba, eu sou novato e não sei configurar bem o mod. como adiciono mobs na white list?

**Comment by seymourimadeit** [comment]
From what I can gather from google translate (as I don't speak Portuguese) you're trying to ask where you can add mobs to the whitelist. To add mobs to the whitelist go to your game directory, then find the config folder. Once you're there click on the guardvillagers-common.toml file find the whitelist option and type in the mob id. Use quotes and separate entries with commas for groups of ids.

**Comment by Mesaya1** [comment]
Thanks!
Edit: This mod is really very good congratulations!
Em ter., 7 de nov. de 2023 23:28, seymourimadeit ***@***.***>
escreveu:
