### ISSUE TITLE
[{Feature Request} 1.16], guard villagers can wield every weapon.

### ISSUE THREAD

**Issue by mettlephaontoms** [seymourimadeit/guardvillagers#15]
guard villagers can wield tools, swords, crossbows, and shields, but they cannot properly wield bows or tridents.
I have tested with drowneds holding channeling tridents during a thunderstorm, and their channeling enchantment does not apply to anything it hits, it would be cool to see a guard villager throwing a channeling trident during a thunderstorm and it actually applying the enchantment to the enemies.

**Comment by rooben777** [comment]
+1 to this, and they should also be allowed to handle moded weapons! (crossbows from vampirism would be totally amazing)

**Comment by seymourimadeit** [comment]
Guards can use modded bows and crossbows in 1.1.10.
