### ISSUE TITLE
Guards won't de-aggro?

### ISSUE THREAD

**Issue by WinterWisteria** [seymourimadeit/guardvillagers#152]
I had to kill a possessed villager and now the guards are pissed at me, I've died a few times and travelled far out of render and returned but I can't get them to de-aggro off of me. Not sure if this is as intended but now I can't trade with my villagers without getting sniped by my own enchanted weapons that I gave them :')

Help?

**Comment by seymourimadeit** [comment]
This is due to the reputation mechanic, if you want to bypass this simply put the player in the blacklist or find a way to make your reputation among the villagers higher.

**Comment by WinterWisteria** [comment]
Cheers, I have my trade center in my basement but now I can't get down
there without being set on fire DX
I have one villager up top so maybe they can vouch for me haha
