### ISSUE TITLE
[1.20.1]Guards cannot shoot arrows with the crossbow in their off-hand

### ISSUE THREAD

**Issue by v191949v** [seymourimadeit/guardvillagers#153]
Whenever the guard is about to fire an arrow from his off-hand crossbow, the guard will repeat the action of reloading the crossbow. After repeating the reloading action a few times, I put their crossbow in their main hand, and it would shoot 2-3 arrows at once, as if the crossbow was enchanted with multi-shot, even though the crossbow didn't have any enchantments.
By the way, another bug: Warden's melee attack cannot disable the player's shield and the guard's shield for 100 ticks. I have confirmed that it is caused by this mod.

**Comment by seymourimadeit** [comment]
Honestly I'm probably going to disable the ability for guards to even use weapons on the offhand because that should only be for shields and food items. Also the bug with the Warden is from forge, not from this mod, report it to them.

**Comment by v191949v** [comment]
Ok, I get it, by the way: would you consider adding my suggestions for this mod?
