### ISSUE TITLE
Guards that I spawn in creative with spawn eggs and guards that I interact with dont attack me

### ISSUE THREAD

**Issue by minecraftedleen** [seymourimadeit/guardvillagers#155]
I'm trying to fight guards and apparently if I use spawn eggs to spawn them in creative or I interact with them to make them patrol and stuff they just don't want to fight me

**Comment by seymourimadeit** [comment]
Cannot recreate, this may be due to the fact you have hero of the village, have the player on the blacklist, or just have another mod messing something up. Please test this alone and if it happens still I will try to investigate further.

**Comment by minecraftedleen** [comment]
ok well guards that I spawn can attack me now (idk why they didn't before) but interacting with them makes them stop attacking me 
https://drive.google.com/file/d/13gCHELQf2AU-jMSYyp96jUneIp5c2Bol/view?usp=sharing

**Comment by seymourimadeit** [comment]
I've tested further and I just cannot recreate the same issue on a pure installation. If this is happening with any other mods installed then it's likely just a mod conflict.

**Comment by seymourimadeit** [comment]
Are there any updates on this or is it safe to close?

**Comment by minecraftedleen** [comment]
I tried it in a new world and its still happening, I don't really want to remove all my mods (I'm using 1.20.1-1.6.3 btw)

**Comment by minecraftedleen** [comment]
I looked at the entity data and it seems that interacting with a guard adds an owner nbt

**Comment by minecraftedleen** [comment]
I did figure out how to set the owner tag to all 0s so that guards can attack me even after I modify their inventory (using repeating command block)

**Comment by seymourimadeit** [comment]
> , I don't really want to remove all my mod

Look, if it isn't happening on a pure instance of guard villagers then it's likely another mod is causing this. Until that is figured out I can not possibly solve this at all. I'm going to close this issue due to the fact you've already found something that fixes this problem.
