### ISSUE TITLE
Zombie Piglins attack guards on sight

### ISSUE THREAD

**Issue by minecraftedleen** [seymourimadeit/guardvillagers#157]
Zombie piglins attack guards on sight, even if I make guards not attack them with the blacklist

**Comment by seymourimadeit** [comment]
This is because of the fact zombie piglins are considered zombies in the code, and since I made all zombie-related mobs attack guards this will happen.

**Comment by minecraftedleen** [comment]
Wait but is there a way to stop this from happening
