### ISSUE TITLE
[{Feature Request} 1.16] Smiths, leather workers, and fletchers, supply equipment to guards.

### ISSUE THREAD

**Issue by mettlephaontoms** [seymourimadeit/guardvillagers#16]
Like a weapon smith can supply an iron ingot to repair an iron golem, all smith professions, leather workers, and fletchers will supply equipment to the guards.

**Comment by rooben777** [comment]
+1 for this, although as of now I cant think of how fletchers will actually help the guards, since they have an infinite amount of arrows.

**Comment by BrisingrAerowing** [comment]
Fletchers could provide different kinds of arrows.

**Comment by seymourimadeit** [comment]
This suggestion is still being kept in mind, but all feature requests must be posted on either the discord or this repo https://github.com/seymourimadeit/guardvillager-suggestions/issues
