### ISSUE TITLE
Textures from resource pack only render the guard_steve_0

### ISSUE THREAD

**Issue by CavalryHasArrived** [seymourimadeit/guardvillagers#161]
I've made a resource pack to add some skins to the guards but only the texture from guard_steve_0 is being used, i can't seem to find a way to load the other models other than changing the one i want to the ![guard_steve_0](https://github.com/seymourimadeit/guardvillagers/assets/61096368/dd07fb7f-9e7f-42df-9a81-e657ce9eed45)
![guard_steve_1](https://github.com/seymourimadeit/guardvillagers/assets/61096368/ac8d9c74-7d52-4969-b573-ebbf9371ff6d)
![guard_steve_2](https://github.com/seymourimadeit/guardvillagers/assets/61096368/62cf00ec-e86e-4d7a-b923-5783f5d9d6db)
![guard_steve_3](https://github.com/seymourimadeit/guardvillagers/assets/61096368/865887d1-7d3f-4405-aeb5-486dd2b02011)
![guard_steve_4](https://github.com/seymourimadeit/guardvillagers/assets/61096368/6a645155-9e7e-44ca-9214-9840092e60bf)
![guard_steve_5](https://github.com/seymourimadeit/guardvillagers/assets/61096368/73ee5eb7-87e2-4a08-8289-c5c62e301c79)
![guard_steve_6](https://github.com/seymourimadeit/guardvillagers/assets/61096368/b70a725e-ef93-4ea0-9501-83a761aad57e)

I've set guard_steve_1 as the new guard_steve_0 ![ihere](https://github.com/seymourimadeit/guardvillagers/assets/61096368/efdc5b1b-ccd8-4165-914a-6180e09e8782)

idk if that's how it works, can u help?

**Comment by seymourimadeit** [comment]
This is because guard_steve_0 corresponds to the plains biome, and you're on a superflat world. If you want something akin to optifine's random mobs I suggest you find another discord because I'm not experienced with that

**Comment by CavalryHasArrived** [comment]
oooooooohhhhhhhhh TYSM i didn't know they where generated related to biomes, i tought all had the same skin no matter what.
