### ISSUE TITLE
[1.20.1]Bow guard is not looking at the target when shooting arrows

### ISSUE THREAD

**Issue by v191949v** [seymourimadeit/guardvillagers#162]
As shown below:
![2023-12-28_22 04 33](https://github.com/seymourimadeit/guardvillagers/assets/137482426/1514ff4c-9aa0-4f59-967a-243a116367e5)
![2023-12-28_22 04 54](https://github.com/seymourimadeit/guardvillagers/assets/137482426/fc79b017-c2a4-42e6-b381-1099f0c072a2)

**Comment by seymourimadeit** [comment]
Vanilla problem with all bow using mobs.
