### ISSUE TITLE
1.18.2 Modpack randomly crashes with Guard villagers installed, is Gossip buggy?

### ISSUE THREAD

**Issue by xFirefalconx** [seymourimadeit/guardvillagers#165]
From time to time the modpack I am working on crashes, randomly. It's hard to trace back but got to do with entities, the bug frequency also increases with entity number. 
I asked on an other github for help and the mod dev said that perhaps, according to the stacktrace I struggle to read, the gossip function might be intertwined in the problem. I'm reporting here in hope you can help somehow, even if it's just a "try ask mod dev xyz". 

https://github.com/iChun/MultiplayerServerPause/issues/7#issuecomment-1880208367 holds most information on the crash but I collected a few that you can also read down below.

According to MSP dev: "One of the classes suggests a crash is happening with whichever mod adds: tallestegg.guardvillagers.entities.ai.goals.VillagerGossipToGuardGoal" - Is this confirmed to be from guard villagers? Can you do anything about it if so?

What is happening exactly:

You're logged in a world, singleplayer or multiplayer doesn't matter in my case. All of the sudden, you might be moving around or just idling, the game starts to freeze entirely, "no response" shows up in the task bar. If you wait patiently, the game will react again, but it has crashed, sending you to the server page?? With an error message. You can re-join the game without any problems, but it can and will happen again, in due time.
The log will show a specific entity, happened already with (untamedwilds:newt, minecraft:villager, minecraft:cow, minecraft:iron_golem, ...) a lot of different entities. It's not the player though! (As far as I could decipher the logs)
It doesn't corrupt the worlds but it does heavily impact the flow and playability of a pack.

A few logs (I copied them from my older crash report in MSP github)

[crash-2023-10-27_02.50.08-server.txt](https://github.com/seymourimadeit/guardvillagers/files/13863353/crash-2023-10-27_02.50.08-server.txt)
[latest(1).log](https://github.com/seymourimadeit/guardvillagers/files/13863355/latest.1.log)

**Comment by seymourimadeit** [comment]
> Is this confirmed to be from guard villagers? Can you do anything about it if so?

It is from this mod. The good news is that it is fixed in 1.19 and up due to me replacing that system altogether, the bad news is that I'm not going to publish a fix for it in 1.18.

Some reasons why:
1. 1.18 is 2 years old and virtually no mods support it anymore.
2. If I made a fix for 1.18 for this one bug, then people would ask me to make more fixes for more older versions, and that'd be a big headache.
3. I have too many things on my plate already and would rather make new features for newer versions rather than spend more time on a version that is barely supported by most mod developers.

Your best option is just to update to either 1.19 or 1.20 OR make a pull request (or get someone else) to fix this issue in 1.18

**Comment by xFirefalconx** [comment]
Thanks for the info. Do you still have the resources available so I (or somebody else) is able to do comparisons and create a pull request? If so, I'd make a fork and attempt it, or so. I'm scared it might get overwritten or unavailable like in other mods that's why i'm asking.
Updating to an other MC version is impossible for my modpack at this point, we're speaking about over 500 mods right now so I try to see where I can still get support and fixes and what I need to purge for pack stability.

**Comment by seymourimadeit** [comment]
> Do you still have the resources available so I (or somebody else) is able to do comparisons and create a pull request? If so, I'd make a fork and attempt it, or so. I'm scared it might get overwritten or unavailable like in other mods that's why i'm asking.

The 1.18 version on the github is public and so is the 1.20 version (on the master branch).
