### ISSUE TITLE
Reputation relative problems of aggressive guards and golems in the config

### ISSUE THREAD

**Issue by betterworld-sjq** [seymourimadeit/guardvillagers#167]
![910c7e6b149b13691f546440a4b814e0_image_ex=65bc6bd8 is=65a9f6d8 hm=3ab944931bb84c08b2f16a9fee8777ce1810bc444a1317edfb2b3855bcd2ac3c = format=webp quality=lossless width=1473 height=95](https://github.com/seymourimadeit/guardvillagers/assets/140177869/f54876db-5173-4de6-99a7-b33b16522474)
I set this above 0 hoping that guards and golems would stay aggressive initially until I've traded with a villager to add reputation. But they're still neutral to me without my aggro.

**Comment by Razor235T** [comment]
Why is it closed without commenting? I have the same issue, the guards are still neutral, even though I killed a lot of villagers and a golem.
