### ISSUE TITLE
1.16 villagers turn into pigs

### ISSUE THREAD

**Issue by Olafoman** [seymourimadeit/guardvillagers#17]
Hello! I had a problem with the villagers turning into pigs when I shift right click them with a sword in my hand. I dont know why it happens and I tried the spawning the villager via egg and a normal villager that I found. in the end they still turn into pigs. Can you help me? I use Aternos servers to play minecraftand use Tlauncher to play a cracked version of minecraft for 1.16. And also I don't know how to code...
![2020-08-03_23 18 27](https://user-images.githubusercontent.com/69158697/89198926-745f1380-d5e0-11ea-9167-4e51cc3a5f2a.png)
![2020-08-03_23 18 31](https://user-images.githubusercontent.com/69158697/89198984-8476f300-d5e0-11ea-9857-adb489a455f6.png)

**Comment by seymourimadeit** [comment]
duplicate #9
