### ISSUE TITLE
Disable Natural Spawn

### ISSUE THREAD

**Issue by mergmer** [seymourimadeit/guardvillagers#174]
Is there a way to disable natural spawning of the guard villagers, i was having some errors and removing the mod stopped my server from crashing (Fabric 1.20.0), i would like to keep the mod but only have them spawn by spawn eggs or when a villager is given a weapon. Thank you

**Comment by seymourimadeit** [comment]
You can disable the datapack that allows them to spawn in villages. 

For future reference please refer to the github listed on the guard villager's fabric version's page, as this is the forge version and thus unaffiliated with the fabric version. 

https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric

**Comment by ToppyTopology** [comment]
> You can disable the datapack that allows them to spawn in villages.
> 
> For future reference please refer to the github listed on the guard villager's fabric version's page, as this is the forge version and thus unaffiliated with the fabric version.
> 
> https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric

hello, where can I find this datapack?
