### ISSUE TITLE
Guards keep causing ticking entity exceptions

### ISSUE THREAD

**Issue by WindowsXPFake** [seymourimadeit/guardvillagers#176]
so basically for some reason whenever a raid happens the villager guards cause a ticking entity exception which is supposed to crash me but I have a mod that prevents that, here's my latest log, my guess is that its caused by some mod incompatibility
[latest.log](https://github.com/seymourimadeit/guardvillagers/files/14620550/latest.log) since there's a similar issue report related to ai It might have something to do with Enhanced AI I'm not entirely sure however because I don't know if it used to happen before or has just started happening.

**Comment by WindowsXPFake** [comment]
I don't actually know how to add labels

**Comment by seymourimadeit** [comment]
Sorry, but we don't support 1.19.2 anymore. If this bug appears in 1.20 then we will fully investigate this issue.
