### ISSUE TITLE
Guard get stuck in certain situations because of carpets (villagers too tbh tho)

### ISSUE THREAD

**Issue by DeMooniC3** [seymourimadeit/guardvillagers#177]
![image](https://github.com/seymourimadeit/guardvillagers/assets/118634784/6bae3da9-a52c-4289-917c-9f60a33bb8c2)

The image above is in a set up, I know, but you can find a situation like this naturally where they actually get stuck, I discovered this while doing a regular survival game, here it is:

![Screenshot_2297](https://github.com/seymourimadeit/guardvillagers/assets/118634784/07ec8925-8047-4d6a-814d-818ffc97ea63)
![Screenshot_2298](https://github.com/seymourimadeit/guardvillagers/assets/118634784/b7b966ff-8cc1-4ad1-9844-282c02016d67)

Their hitbox is also too tall and they can't fit in a 1x2 gap if they are standing on a carpet (I mean, yeah, it's also the case for vanilla villagers, zombies, etc.) IDK how the guard got there to begin with tho since afaik they spawn at the center of the village lol

![image](https://github.com/seymourimadeit/guardvillagers/assets/118634784/d8682f1a-51a9-4e06-9b77-29267186e4e8)

So I don't know if the issue here is they can't path find properly if there are carpets because they see a carpet as a full block or if it's simply that their hitbox doesn't fit, or both lol

IDK why Mojang made the hitbox for villagers and every single other humanoid mob so much taller than that of players

![image](https://github.com/seymourimadeit/guardvillagers/assets/118634784/8d555777-7b42-4ac2-a8e6-4e8dafeb6f8f)

**Comment by seymourimadeit** [comment]
>  mean, yeah, it's also the case for vanilla villagers, zombies, etc.)

This should honestly be reported to mojang then.

**Comment by seymourimadeit** [comment]
I will see if I can fix this for guards only, but I can't do anything for the other vanilla mobs.
