### ISSUE TITLE
Guards randomly aggro, even when player has only just spawned / found village

### ISSUE THREAD

**Issue by goldrat1** [seymourimadeit/guardvillagers#179]
Hi there,
I've found while exploring my world that every now and then a Guard will just decide that I'm an enemy and begin attacking me after I hadn't had any reputation changes with any village. I hadn't hit any villagers, or traded with them, or so much as gone near the villages that have this happen.
Interestingly it's usually only one isolated Guard that does this, the others surrounding it don't aggro at all.
I've changed the config to have the automatic Guard aggro level at -999 and this is still happening.

Is there a way to just turn off Guard aggression altogether if this isn't something that is fixable?
Thanks!

**Comment by seymourimadeit** [comment]
Does this issue happen when the mod is isolated? Another mod may be adding something to the guard's ai to make them behave this way.

**Comment by goldrat1** [comment]
I've tried isolating it with any mod I can think of in my list that would affect Guard/Villager AI or optimisation mods and this doesn't seem to happen when isolated, so some other mod conflict is probably the case.
I've attached the main list of the mods that I have (it is a lot) and the mod list that I've tried that hasn't replicated the problem. 

[mod-list-main.txt](https://github.com/seymourimadeit/guardvillagers/files/14626485/mod-list-main.txt)
[mod-list-testing.txt](https://github.com/seymourimadeit/guardvillagers/files/14626484/mod-list-testing.txt)

The main list's a bit too big to do the usual 50/50 issue test but if it comes to that I guess I'll have to try.
Have you seen problems with any of the mods listed, or ones I should try and test with?
And is there a way to disable Guard aggression entirely?
Thanks for your quick response!

**Comment by seymourimadeit** [comment]
This is possibly an issue with the origins mod as another mod may have added compatibility for it to make guards attack different teams. 

Try putting "minecraft:player" in the guard villager blacklist config to disable guards attacking players entirely

**Comment by goldrat1** [comment]
I'm pretty sure this has fixed it, though due to the unreliability of replicating the issue I can't guarentee it. I'll close the issue anyway.

**Comment by goldrat1** [comment]
Turns out it was still happening, but I think I found the cause!
By default, the Improved Mobs mod gives a 10% chance for Neutral mobs to be aggressive by default. This explains why it was only one or two Guards that were doing this in each village!
