### ISSUE TITLE
Missing Zombie Village

### ISSUE THREAD

**Issue by Fizzie617** [seymourimadeit/guardvillagers#18]
Ive noticed a bunch of zombie villages spawn but there’s nothing there. Just a bunch of roads and zombie villagers burning up with a few cats. No buildings what so ever just the npcs and the roads. Sometimes they spawn and work fine but most of the time I find one there completely gone. I’ve reinstalled the mod and removed all my other mods and they still won’t spawn.

**Comment by seymourimadeit** [comment]
This mod doesn't modify zombie villages at all.
