### ISSUE TITLE
[NeoForge] Crash on launch

### ISSUE THREAD

**Issue by ffuentesm** [seymourimadeit/guardvillagers#186]
With no major change in the 1.20.6, most 1.20.5 mods are compatible with it, but looks like NeoForge removed the FinalizeSpawn method in 20.6.50-beta.

Minecraft version: 1.20.6
Modloader: NeoForge
Forge version: 20.6.72
Environment: Singleplayer
Mod version: guardvillagers-2.1.1-1.20.5.jar
![image](https://github.com/seymourimadeit/guardvillagers/assets/44974827/4d1c1f5c-c27e-4299-b148-ca3ef95ab7a2)

**Comment by seymourimadeit** [comment]
Hate to say it but I'm gonna have to port straight to 1.21 and ignore 1.20.6
