### ISSUE TITLE
Zombie Guard Villagers

### ISSUE THREAD

**Issue by MLGLuigiGamer** [seymourimadeit/guardvillagers#19]
Uhh When a guard dies to a zombie it becomes a pile of missing textures. can you give them their own zombie villager textures?

**Comment by seymourimadeit** [comment]
pictures please, the zombie villagers are supposed to spawn with a randomized profession texture.

**Comment by Rutes** [comment]
I can confirm that when guard villagers get turned into zombies, it does sometimes make their texture freak out

![image](https://user-images.githubusercontent.com/5608566/105615131-d4ff2a00-5d93-11eb-8755-deca496c9e4e.png)

![image](https://user-images.githubusercontent.com/5608566/105615140-ddeffb80-5d93-11eb-95e8-8d11e5467e24.png)

**Comment by seymourimadeit** [comment]
Like I said before, this ones most likely caused by some other mod not making their villager profession textures for zombie villagers.
