### ISSUE TITLE
Game Crash when spawning Guard Villager (NeoForge)

### ISSUE THREAD

**Issue by ItsMeMcNoob** [seymourimadeit/guardvillagers#193]
"The game crashed whilst ticking entity
Error: java.lang.NoClassDefFoundError:
net/neoforged/neoforge/common/ToolActions
Exit Code -1"

**Comment by ItsMeMcNoob** [comment]
I'm new to GitHub, so do you know how I can fix this bug?

**Comment by seymourimadeit** [comment]
Update your mod version, it fixes the crash
