### ISSUE TITLE
Crossbow not reloading, Mixed AI between sword and bow in hands

### ISSUE THREAD

**Issue by Mostovm** [seymourimadeit/guardvillagers#194]
Fabric 1.21

Stuck between trying to move back, attack with sword, or reloading crossbow it looks like the guard wont shoot or reload only kick. (Does have a sword in offhand)

Also there should be a trust system between guards and command your squad regardless of hero of village effect. Defenitely a good mod so far but I'd also love to see an army of guards follow your lead and set post around your bases, join pvp and such. Should also have inventory for food and eat when safe. Now another stretch is having gaurds follow and ride on player owners horses, I get thats a lot to implement these features but I think it'd be the best villager mod and becoming a needed implementation to minecrafts base game. Thanks 🙏

**Comment by seymourimadeit** [comment]
Sorry but we don't support the fabric version, this is the forge repository.  You can find the fabric version here https://github.com/mrsterner/GuardVillagers/issues
