### ISSUE TITLE
[1.21] [Neoforge] Ticking entities crash 

### ISSUE THREAD

**Issue by ffuentesm** [seymourimadeit/guardvillagers#195]
Crash Log: https://github.com/Bawnorton/NeruinaAutoReports/issues/99

guardvillagers-2.2.5-1.21.jar 
Neoforge: 21.0.76

Mod is causing all hostile mobs to tick. 
Passive mobs are unaffected

**Comment by seymourimadeit** [comment]
Due to neoforge changes
