### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SGZ-Creations** [seymourimadeit/guardvillagers#196]
NeoForge : 21.0.59  used on
NeoForge : 21.0.61 mod installed on

Mod version 2.2.6

MC version: 1.21.0

Crash with new version:
[crash-2024-07-09_06.48.35-server.txt](https://github.com/user-attachments/files/16138153/crash-2024-07-09_06.48.35-server.txt)

**Comment by seymourimadeit** [comment]
use latest version of neoforge or downgrade mod version
