### ISSUE TITLE
Crash when trying to render Guard Villager

### ISSUE THREAD

**Issue by Destroy5000** [seymourimadeit/guardvillagers#197]
I am a server owner, and when I attempt to put the mod on my server, I notice that it crashes the game when I near a village, and the only way to fix it is to delete the mod. 

The error message was Network Protocol error.

Im using Fabric And playing on 1.21

**Comment by seymourimadeit** [comment]
Sorry we don't support the fabric version. Here is the correct repo: https://github.com/mrsterner/GuardVillagers
