### ISSUE TITLE
Guard villager ambient noise

### ISSUE THREAD

**Issue by HacoKavanah** [seymourimadeit/guardvillagers#199]
![image](https://github.com/user-attachments/assets/da8a5b27-f53f-4f60-850c-ef520fbea7a3)
Looks goofy

**Comment by seymourimadeit** [comment]
What version is this on? I can't seem to recreate this on 1.21 or on 1.20.1

**Comment by HacoKavanah** [comment]
1.21 Fabric, Version 2.1.2 which is the newest on modrinth

**Comment by seymourimadeit** [comment]
This is not the repo for the fabric version, please report it to their GitHub found on their curseforge page
