### ISSUE TITLE
Accidentally giving the sword

### ISSUE THREAD

**Issue by Mikeliro** [seymourimadeit/guardvillagers#2]
It would be nice if you switched to shift + right button to give sword to villager, to avoid giving sword accidentally.

**Comment by seymourimadeit** [comment]
its already fixed as of currently, see https://github.com/seymourimadeit/guardvillagers/commit/c9e378c481d273b7f4ac814d8500d974e5dc6d82#diff-3acc7a761065d1fdfaff916c3fc5a652

this fix will be included in the next update once i let the guard spawn with their biome specified texture variants if they spawn in a desert, snowy, savanna or taiga village
