### ISSUE TITLE
Suggestion: Guardposts

### ISSUE THREAD

**Issue by rooben777** [seymourimadeit/guardvillagers#20]
A block, that could turn nearby guards/villagers into a Sentry, that will patrol only around the vincity of the guardpost. if a bell is present in the post, and the guard suddenly has to deal with a somewhat large amount of hostiles, he should be allowed to ring the bell, thus alerting the villagers nearby, and calling any close guard for back up. iron golems should have the tendency to visit from time to time nearby guardposts

Weapon rack: can be used to place weapons in for decor, if a guard recognises the weapon in the rack as better, we should be allowed to switch weapons. if hes nearby comrades are enquiped with a certain class of weapons (swords for example) the guard could switch to a different class of weapones to help diversify the squad and make it more effective 

armor stands: should have similar functions to the weapon rack (guards being able to interact with it)

Guardpost banner: a banner placed in a guardpost will automaticly turn into a "Guardpost banner", banners of the same color placed in a certain range around the guard post will mark a patrol routh for guards to choose to perfom once in a while, guardposts with matching banners will be a patrol routh that the Sentries assigned in that guardpost will continuosly perform. 

Thats it for now, hope its not too overwhelming for a single suggestion, and I hope the Moderator will fine this useful :)

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
