### ISSUE TITLE
Whitelisting & Blacklisting

### ISSUE THREAD

**Issue by RandomGemz** [seymourimadeit/guardvillagers#206]
I Can't add to either of them I've tried with other mods that the same feature and works but with this one it doesn't allow me to add any creatures to the list

**Comment by seymourimadeit** [comment]
How are you adding the mobs to the lists? Via GUI or text editor? 

If the GUI isn't working for you then try using notepad to edit the guardvillagers-common.toml file (located in the configs folder)

**Comment by seymourimadeit** [comment]
Gonna have to close this since there's been no response for over two weeks. Please elaborate on your problem and I will reopen
