### ISSUE TITLE
Guards are seeing me as hostile

### ISSUE THREAD

**Issue by Blazier1** [seymourimadeit/guardvillagers#209]
I have the mod that makes my first ever spawn into a world be in a village and the guards instantly see me as an enemy and start attacking me.

**Comment by seymourimadeit** [comment]
Sorry for the late response, but have you've tried checking if you have any mods like AI Improvements? That mod has been implicated in causing this problem.

Also sometimes pre-made modpacks configure it so guards attack you by default, so you should go ask them if that's the case

**Comment by seymourimadeit** [comment]
Gonna have to close this due to inactivity. Of course, this will be reopened if you give more detail/an update on this issue
