### ISSUE TITLE
Wandering Traders into Guards

### ISSUE THREAD

**Issue by WenXin20** [seymourimadeit/guardvillagers#21]
Could the ability to turn a Wandering Trader into a guard be added? If their trades are useless, then maybe they could become guards instead.

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.

**Comment by WenXin20** [comment]
Sure!
