### ISSUE TITLE
crush

### ISSUE THREAD

**Issue by Kevin9097987** [seymourimadeit/guardvillagers#21]
Hi I changed the configuration but the game seems to crash and cannot be opened

**Comment by seymourimadeit** [comment]
Please send a crash log so we can accurately see what the issue is.

**Comment by Kevin9097987** [comment]
[latest.log](https://github.com/seymourimadeit/guardvillagers/files/6698836/latest.log)

**Comment by seymourimadeit** [comment]
You misspelled true as 'ture', please correct that in the config file.

If you want to blacklist a mob, put the mobs id in the Mob Blacklist config option, as per this example.
["minecraft:creeper"]

**Comment by Kevin9097987** [comment]
lol  I didn't even notice that😂
