### ISSUE TITLE
Guards Perma Aggro

### ISSUE THREAD

**Issue by XDTRex** [seymourimadeit/guardvillagers#22]
i accidentaly hit a villager, now every single guard (and iron golem) is after me, including in different villages. they have killed me like 15 times, when i only hit a villager ONCE, please make it so guards dont attack the player (i cant find a related config in the config file either so dont ask about that)

**Comment by XDTRex** [comment]
dont know if there is a mod incapability that is making this issue, or if it is just the mod itself

**Comment by seymourimadeit** [comment]
Iron golems attacking you when you have a low village reputation is a vanilla feature, guards also doing that is a mod feature. The only way to make them not attack you is raise up your village reputation via trading or other things.
