### ISSUE TITLE
[{Feature request} 1.16] Shepherds shear pumpkins to spawn golems.

### ISSUE THREAD

**Issue by mettlephaontoms** [seymourimadeit/guardvillagers#22]
Imagine a scenario where a shepherd is being attacked by enemies but there are no more guard villagers and the shephard runs into this structure.
![2020-08-09_01 15 07](https://user-images.githubusercontent.com/69108092/89726246-f171fa80-d9dd-11ea-9432-7f6b7805e963.png)

Perhaps the tool smith would supply shears to the shepherds, and shepherds without shears could not shear pumpkins.

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
