### ISSUE TITLE
Loot Table Bug

### ISSUE THREAD

**Issue by Githubuser2977** [seymourimadeit/guardvillagers#221]
Somehow, mainhand items switch with offhand items and vice versa.

**Comment by seymourimadeit** [comment]
Could you please elaborate on this? This could just be guards randomly being left handed.

**Comment by Githubuser2977** [comment]
I created a datapack that restricts specific items to the main hand and requires bread and a shield for the off hand. However, for some reason, about 1 in 10 spawned guard villagers have this configuration reversed, with bread in the main hand and the specific main-hand items in the off hand. 

I didn’t realize that guards could be left-handed! Is that a feature? It would make sense if they have some randomness in their item placement.

**Comment by seymourimadeit** [comment]
All mobs can be left handed

**Comment by seymourimadeit** [comment]
Will close for now unless it's not just a thing with guards being left handed
