### ISSUE TITLE
[1.16.5 Bug] Guard village transformation cannot be canceled

### ISSUE THREAD

**Issue by GoldenTotem** [seymourimadeit/guardvillagers#224]
Minecraft 1.16.5  Forge 36.2.35  Guard 1.2.3

When a guard is hit by lightning, it will transform into witch. But the transformation is not cancelable.

How to recurrence:

Install mod [Crafttweaker](https://www.curseforge.com/minecraft/mc-mods/crafttweaker/files/5007325), create a new script and write
```
CTEventManager.register<MCLivingConversionPreEvent>(event => {
    if (event.outcome == <entitytype:minecraft:witch> && (event.entity.type == <entitytype:minecraft:villager>)) {
        event.cancel();
    }
});
```
villagers will not transform into witches any more, but if you replace minecraft:villager with guardvillagers:guard, it will stop working. It may cause by that Guard villager mod does not use MCLivingConversionPreEvent like vanilla.

If you install mod [Not enough gamerules](https://www.curseforge.com/minecraft/mc-mods/not-enough-gamerules/files/3718142), and run command `/gamerule doTransformations false`, the problem is visible too, which villagers will stop transforming but guards not.

**Comment by seymourimadeit** [comment]
1.16.5 is unsupported
