### ISSUE TITLE
Guard villagers crash, 1.20.1-1.6.7 "Colliding entity with block"

### ISSUE THREAD

**Issue by Sageking10** [seymourimadeit/guardvillagers#226]
[crash-2024-10-28_18.02.00-server.txt](https://github.com/user-attachments/files/17549265/crash-2024-10-28_18.02.00-server.txt)
The server crashed whilst fighting some scorpions from the Enemy Expansion mod. I guess a Scorpion was fighting a Guard Villager.

**Comment by seymourimadeit** [comment]
Enemy Expansion is a MCreator mod and thus can lead to hard to trace conflicts with other mods, you should try reporting this bug to them first. If this bug is found to be on this mod's side then I will reopen this issue
