### ISSUE TITLE
Guard Villagers and Easy Villagers compatibility

### ISSUE THREAD

**Issue by Dwayne5043** [seymourimadeit/guardvillagers#227]
Guard Villagers and Easy Villagers both use **Shift + Right-Click.**

Minecraft Version: 1.21.1
NeoForge Version: 21.1.76

Easy Villagers lets you _pick up villagers_.
> Version: 1.1.23

Guard Villagers lets you _equip villagers with weapons_.
> Version: 2.3.0

However, Easy Villagers **"overwrites"** the function of Guard Villagers, so with **Shift + Right-Click** you can only pick up villagers and can't equip them with weapons. Also, you can’t change the keybinds for either mod.

**Comment by seymourimadeit** [comment]
Trying to recreate this issue brings no results as I can still pick up villagers and also convert villagers to guards with a sword or crossbow

Do you have any other mods that could be interfering?

**Comment by Dwayne5043** [comment]
> Trying to recreate this issue brings no results as I can still pick up villagers and also convert villagers to guards with a sword or crossbow
> 
> Do you have any other mods that could be interfering?

Hi yes I solved it, I have another mod that lets you pickup things and apparently villagers called "carry on", I just changed the keybinds for carry on and now it works.

Thank you and sorry for the inconvenience.
