### ISSUE TITLE
Why Do Guard Villagers with Crossbows Keep Missing Their Shots?

### ISSUE THREAD

**Issue by Jacksoon44** [seymourimadeit/guardvillagers#229]
Hi everyone,

I’ve been using the Guard Villagers mod in Minecraft, and I’ve noticed that the guards equipped with crossbows seem to miss their shots a lot. It happens even when the target isn’t moving too much.

https://github.com/user-attachments/assets/1aa94943-9cca-455a-b3da-723849a6bf96

Here are some details about my setup:

Minecraft Version : 1.21.1 

Behavior Observed: Guards with crossbows fire at mobs but often miss. In one instance, I fenced in a mob, making it an easy, stationary target, yet the guard didn’t hit a single shot. This seems to happen frequently during my playthrough, even when the guards should have a clear and easy shot.

Has anyone else experienced this? Could it be a bug, an intentional feature for balance, or possibly a conflict with another mod?

I’d appreciate any insights or solutions! Also, if this is a bug, should I report it to the developer?

Thanks in advance! 😊

**Comment by seymourimadeit** [comment]
Are you using the fabric version? I haven't experienced this in dev or personal plays myself, so it could be a problem with the fact you're using the fabric version (which was not made by us and should be reported to their github instead) or another mod interfering

**Comment by Jacksoon44** [comment]
Ops! My apology, should have checked before writing here, i will make a report to their github(fabric version) instead. Thanks for the prompt reply.
