### ISSUE TITLE
Mod compatibility Vampirism

### ISSUE THREAD

**Issue by VirayaDraco** [seymourimadeit/guardvillagers#23]
Hi, i have the mod Vampirism, and with your mod loaded, the iron golems attack and kill the Vampire Hunters in towns, without your mod iron golem dont attack Vampire Hunters, is there any way to solve this issue?

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
