### ISSUE TITLE
Datapack not working for 1.6.9, forge 1.20.1

### ISSUE THREAD

**Issue by YuliaS11** [seymourimadeit/guardvillagers#237]
\data\guardvillagers\loot_tables\entities

[guard_armor.json](https://github.com/user-attachments/files/18252901/guard_armor.json)

\data\guardvillagers\loot_tables\entities\armor_sets

[armor.json](https://github.com/user-attachments/files/18252902/armor.json)

Datapack not working for new version despite matching the new 1.21 datapack format. Instead, all the guards have lost held items entirely.

**Comment by seymourimadeit** [comment]
Try using this for the guard_armor.json instead
https://pastebin.com/krFzcmsY
You seem to have accidentally put two entries for the offhand slot.
