### ISSUE TITLE
Please have an option for guard villagers to not attack players

### ISSUE THREAD

**Issue by codejedi-ai** [seymourimadeit/guardvillagers#29]
I often misclick  and hit a guard villager in my own village or get hit by an archer villager while wearing the thorns enchanted armor causing me to be violently exiled. So please add an option to make the guard villagers passive towards players.

**Comment by seymourimadeit** [comment]
Suggestions go in https://github.com/seymourimadeit/guardvillager-suggestions/issues

**Comment by codejedi-ai** [comment]
I found a fatal flaw in the mod that can ruin any SMP servers that use the mod.

**Comment by seymourimadeit** [comment]
Please describe it and open a separate issue for it.
