### ISSUE TITLE
Guard villagers attack the spot where a dragon from Ice and Fire died until you relog

### ISSUE THREAD

**Issue by Kuusotare** [seymourimadeit/guardvillagers#30]
Title. After the dragon is dead, guards continue to attack the spot where it died, even after you harvest it and the skeleton is no longer there. Issue persists even with skeletons disabled.

**Comment by Kuusotare** [comment]
On 1.16.1*

**Comment by seymourimadeit** [comment]
this is ice and fires fault, all mobs do this, not just guards
