### ISSUE TITLE
Some small suggestions.

### ISSUE THREAD

**Issue by 012phuong** [seymourimadeit/guardvillagers#32]
I had used this mod for a pretty long time since 1.14 as a way to protect the villager from the dangerous threats from other mods in my modpack, recently I noticed that the **Ewewukek's musket mod** had updated to 1.15, it would be nice if you can make your 1.15 mod to be compatible with the musket mod, it will help us build stronger guards to protect the village (which isn't very helpful since the best equipment pillager can equip is a crossbow loaded with a firework but it will help us get rid of the logistic burden). And if for some reason that can't be done, I hope you can add give the guard ability to use crossbow from different mods like **Dungeons Gear**...

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
