### ISSUE TITLE
Guard animation/model rendering may be broken with Optifine Render Regions

### ISSUE THREAD

**Issue by NighthowlerStudios** [seymourimadeit/guardvillagers#32]
Currently investigating an issue with mob spawning where, if Render Regions is on, there is a stateleak leading to it spamming "opengl error 1281 value must be neither zero nor negative."

My two suspected mods are Improved Mobs and Guard Villagers.  I'm still actively searching but I did notice you added custom mob rendering that seems new to me.  So I sent this here to see if you might need to clean up your rendering code.

I know it can be frustrating to deal with Optifine but I'm here to test anything or give suggestions if you wish.  Thanks

**Comment by seymourimadeit** [comment]
This was probably just a bug with optifines first 1.17 release not adapting itself well to the new rendering system.

**Comment by NighthowlerStudios** [comment]
> This was probably just a bug with optifines first 1.17 release not adapting itself well to the new rendering system.

nope, this bug was in 1.16.5 and was caused by Improved Mobs.  the issue can still be closed but yeah it wasn't 1.17 like you tried to claim.
