### ISSUE TITLE
Compatibility with Villagers Respawn mods by MacTso

### ISSUE THREAD

**Issue by PhantomH17** [seymourimadeit/guardvillagers#33]
As the title said, it would be nice to have this mod compatible with villagers respawn mod since they die a lot.

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
