### ISSUE TITLE
Guards wont take armor

### ISSUE THREAD

**Issue by lilanimal13** [seymourimadeit/guardvillagers#33]
Im playing with the mod on my server with my friend and we cant put armour on our guards. We can recruit them as normal but they wont take any sort of armour. So you know why this happens? P.S We are playing on 1.16.5

**Comment by seymourimadeit** [comment]
Players will only be able to open a guards inventory if they have hero of the village.

**Comment by lilanimal13** [comment]
Oh ok, thank you
