### ISSUE TITLE
emerald Dupe

### ISSUE THREAD

**Issue by loonywolf** [seymourimadeit/guardvillagers#34]
don't know if it on all Versions but 16.1 got a massive dupe 
Make a Villager a guard then sneak and spam emeralds on him he  give giving you emeralds and i mean Lots, LOl i made 4 stacks of  emerald blocks in about a 20 seconds  

Ps works On the new Version 16.1of guards too 

LW

**Comment by seymourimadeit** [comment]
nullified by the fact that guards now have an inventory
