### ISSUE TITLE
1.16.5 ticking entity Crash

### ISSUE THREAD

**Issue by Lerrycapetime** [seymourimadeit/guardvillagers#37]
[crash-2021-09-04_08.55.45-server.txt](https://github.com/seymourimadeit/guardvillagers/files/7110177/crash-2021-09-04_08.55.45-server.txt)

**Comment by seymourimadeit** [comment]
Does this crash occur when a guard is normally fighting a mob with a bow?

**Comment by Lerrycapetime** [comment]
It only occurs with a bow but also it seems to be random, I've never had any issues with crossbows or swords so far, but could I look into that more.
