### ISSUE TITLE
[Suggestion][1.16.4] Make player-promoted Guard always friendly to player

### ISSUE THREAD

**Issue by drakray** [seymourimadeit/guardvillagers#37]
Like the title says, could it be possible to make the Guard that where given gears by the Player be friendly(passive) to that player, or maybe add a configurable item that when given, make it friendly(passive) to that player, and another to make it friendly(passive) to all player?

**Comment by seymourimadeit** [comment]
Guards being permanently friendly to the player will not be added.

**Comment by drakray** [comment]
Sad, but I understand.
I'll wait for Enigmatic Legacy to have a config to blacklist them from the second curse of the Ring of Seven Curses then.
