### ISSUE TITLE
Guard Villagers attack me for no reason

### ISSUE THREAD

**Issue by RudiPrico** [seymourimadeit/guardvillagers#38]
I wanted to make a flat world just surviving alongside the guard villagers against the raids, but when I set to survival they started attacking me. I had to kill some villagers while in creative. I have also turned the gamerule forgivedeadplayers to true. Does not work. Please help.

**Comment by carlosmiguel-19** [comment]
si me pasa lo mismo a mi también me matan y vuelvo para recoger mis cosas y vuelven a matarme

**Comment by seymourimadeit** [comment]
This is because you have a low village reputation, to fix this either move to a new village or find a way to up your reputation with the villagers by trading with them.
