### ISSUE TITLE
[Feature Request] [1.15.2] Add compatibility with Vampirism.

### ISSUE THREAD

**Issue by mjlmjl888** [seymourimadeit/guardvillagers#4]
If possible you could make it so when you are in a vampire village the guards look like vampires.

**Comment by rooben777** [comment]
+1 for this

Also, guards should turn on anyone who harms the nearby Vampire Hunters, since they too protect the village.

**Comment by seymourimadeit** [comment]
This suggestion is still being kept in mind, but all feature requests must be posted on either the discord or this repo  https://github.com/seymourimadeit/guardvillager-suggestions/issues
