### ISSUE TITLE
Regular villagers run away like cats when you get near them

### ISSUE THREAD

**Issue by MrsShanTheBee** [seymourimadeit/guardvillagers#40]
I'm playing with this mod in 1.16.5 and the guard villagers work fine but for some reason the rest of the villagers run away with the same speed and sporadic movements as cats do. I removed the mod and they all went back to normal.

**Comment by seymourimadeit** [comment]
Can I see your mod list? Playing with this mod alone doesn't seem to have those behaviors.

**Comment by seymourimadeit** [comment]
Closing until further information is given.

**Comment by MrsShanTheBee** [comment]
So sorry about the time! It seems like it was conflicting with the Regrowth villager mod. We took out your mod and they went back to normal even with the Regrowth mod and then we put your mod back and they weren't running away like cats anymore.
