### ISSUE TITLE
Guards are the same mob type with iron golem?

### ISSUE THREAD

**Issue by kihgy** [seymourimadeit/guardvillagers#41]
I have charm installed and put a tier 4 beacon to heal the village. Currently the beacon only villagers, not golem ... and guards. So is the guards the same type of mob woth golems? Could they be the same type with normal villagers instead?

**Comment by seymourimadeit** [comment]
this is a charm problem, the mod only checks for mobs that age, for some reason, go ask the mod creator for charm for support with this mod.
