### ISSUE TITLE
Ultilizing guards outside of a village

### ISSUE THREAD

**Issue by warning-djkajslh** [seymourimadeit/guardvillagers#42]
Hello, not sure if this is implemented but I want to use guard villagers for my personal base, and of course there will be no beds nor villagers around the vicinity.

My question is whether the guards will stilll be around my base without any villagers, or they will just go away similar to golems?
If the answer is no, then can you make it so players will be allow to use guards for their bases?

**Comment by seymourimadeit** [comment]
You can use fences to surround the guard to make them stay near the base.

For future reference this is not a questions form, as such please only post bug reports.
