### ISSUE TITLE
Feature suggestion: Ability to claim guards when they totally trusted the player.

### ISSUE THREAD

**Issue by kihgy** [seymourimadeit/guardvillagers#42]
I read that guards will follow you when you have Hero of the village, but when the effect goes off, the will stop, so here is my suggestion in recruit a guard into obey you forever.

Condition: The player must have the maximum reputation in the village, plus, must have Hero of the village level III or V? Then you can now recruit village guards into protecting your own home and follow you around. When a guard accept your offer, he will follow you, obey your command and protect you over other villagers, basically a tamed wolf, but are heavily equipped. The commands are simple: Sitting, Patrolling designated area and following the player.

Recruiting by giving them valuable and useful items, like a diamond armor piece, and they will join you forever.

Patrolling guards wont go far, they will return to the patrolling spot if strayed too far away. Immediately after you switch the command to patrol, an imvisible home point is registered, and guards will return to it, when switched to follow or sit, this homepoint is deleted.

**Comment by seymourimadeit** [comment]
Guards obeying you forever will not be added.
