### ISSUE TITLE
Add compatibility with easy villagers mod 

### ISSUE THREAD

**Issue by templarscoutb** [seymourimadeit/guardvillagers#44]
I acted as liaison to get the pickup feature of easy villagers to work with the shift right-clicking to assign a villager as a guard to work. 
Now the only thing that would make the two mods fully compatible would be to allow guard villagers  to be picked up when using easy villagers mod

**Comment by jengendler** [comment]
+1 for this.

Perhaps just right-clicking a guard to open their inventory, just like you right-click an employed villager to open the trade window, therefore keeping consistency with villager GUI interaction. This allows shift+right-click to be available for Easy Villagers pick-up, and still allows shift+right-clicking with a sword or bow in hand to assign an unemployed villager or nitwit as a guard for this mod.

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
