### ISSUE TITLE
[Suggestion]: Add a "Mob Attack Blacklist" when turning on "Attack all Hostiles" feature.

### ISSUE THREAD

**Issue by Adodii** [seymourimadeit/guardvillagers#45]
Hi, quick suggestion. Could you add a feature where i can blacklist guards from attacking a mob/mobs when turning on the "attack all hostiles" feature? Because i'm sick of guards and creepers constantly fighting each other and making holes everywhere in my world.

**Comment by seymourimadeit** [comment]
added
