### ISSUE TITLE
Guards give infinite Items

### ISSUE THREAD

**Issue by Marihenshin** [seymourimadeit/guardvillagers#47]
When you Shift + Right Click a guard with ANYTHING, then you Shift + Right Click him again with the same item, it will drop Over and Over and Over

Thus giving you as much as you want.
While that is nice and all, it is kinda a cheat.

Minecraft: 1.16.4
Forge: 35.1.13
guardvillagers-1.16.3-1.1.5

**Comment by seymourimadeit** [comment]
fixed in dev
