### ISSUE TITLE
Combat AI

### ISSUE THREAD

**Issue by KTZ6** [seymourimadeit/guardvillagers#5]
The guards are zealous, but dumb. They will jump off buildings, sometimes to their own deaths, to chase zombies instead of running down the stairs/ladder and out through the door. They will not fight back against mobs such as skeletons when attacked by skeletons. Friendly fire tends to cause more damage than the fight with the actual mobs. I'm wondering if you could improve their path finding abilities, allow them to attack other hostile mobs, and reduce the amount of friendly fire there is. Honestly, I'm not sure how difficult those 3 things are to do. I really like this mod and hope it can continue to improve.

**Comment by seymourimadeit** [comment]
improvement of ai is being planned and is being worked on as we speak, crossbow guards that are reloading will attempt to find another spot that they can move to, the pathfinding ablities is probably just a vanilla bug but i will look into it, allowing them to attack other hostile mobs is already configurable but i plan to make it alot more customizable and the friendly fire i will attempt to fix that
