### ISSUE TITLE
Guard villagers

### ISSUE THREAD

**Issue by yqminecraftplayer** [seymourimadeit/guardvillagers#50]
Why the guard villagers didn't pick up the armor on the floor?

**Comment by FlameyFaucet** [comment]
Pretty sure that's an old feature. Now they don't pick up things.

**Comment by yqminecraftplayer** [comment]
Is it just for 1.14.4?

**Comment by seymourimadeit** [comment]
That feature is just for 1.14.4. For modern versions you must have hero of the village in order to access the guards inventory.
