### ISSUE TITLE
console errorss

### ISSUE THREAD

**Issue by willownezz** [seymourimadeit/guardvillagers#52]
nothing is crashing but when I look at one of the guards my console get a constant stream of errors that only stop when  I look away.

![Screenshot_116](https://user-images.githubusercontent.com/3631656/102729354-4ce5ba80-42e5-11eb-9994-b4441e8ae352.png)

**Comment by willownezz** [comment]
https://paste.ee/p/McCMq

**Comment by seymourimadeit** [comment]
paste link seems to be gone, please reopen this with a non expiring pastebin link.
