### ISSUE TITLE
[Suggestion] Custom Config Guard HP (Stats)

### ISSUE THREAD

**Issue by papa3boyz** [seymourimadeit/guardvillagers#53]
Hi dev, i 100% like this mod and today i tested it on NO sleep night in single player and they just very weak. Please add custom config for health, attack or etc for guards also prevent them turn into zombies. Thanks

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
