### ISSUE TITLE
Hello, I still haven't figured out how to change the resident's model to Steve's model

### ISSUE THREAD

**Issue by Ivan12iv56** [seymourimadeit/guardvillagers#53]
Hello, I still haven't figured out how to change the resident's model to Steve's model and so the file guardvillagers-client.toml. I couldn't find it, please can you explain in detail how to change the model, in which folder the file is located, how to completely change it so that the model changes???

**Comment by seymourimadeit** [comment]
(minecraft folder)/config/guardvillagers.client.toml

for future reference this github page is not a questions form, further questions must be posted on the discord.
