### ISSUE TITLE
[Suggestion] guards ignore mobs with name tags

### ISSUE THREAD

**Issue by draklorx** [seymourimadeit/guardvillagers#54]
I picked up some guards using a mob catcher mod and released them into my base. They immediately took off  across the entire setup to a place about 50 blocks away where I had my iron farm setup. They couldn't hurt the zombie named Steve inside but they desperately wanted to ignoring all other threats because it was very important to harass Steve.

Would be nice if the guards would ignore name taged mobs. I'm also open to other ideas.

**Comment by Brun333rp** [comment]
yeah, perhaps it should be configurable wheter they attack nametagged mobs. but they should still attack, if provoked

**Comment by draklorx** [comment]
I'm good with that. I'd also be good with not going after mobs that there is not available path to get to, but I don't know how difficult that would be to program.

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
