### ISSUE TITLE
1.18

### ISSUE THREAD

**Issue by FalloutNVFanGene** [seymourimadeit/guardvillagers#54]
Villagers don't attack creepers (I guess to avoid them blowing up villages?) And skeletons are also considered passive. But they attack me when I rely on the village guards to protect it.

**Comment by seymourimadeit** [comment]
Works as intended.

You can enable guards attacking all hostile mobs in the config.

**Comment by FalloutNVFanGene** [comment]
Is there a video on how?

**Comment by FalloutNVFanGene** [comment]
So, Where is the Config file? Is there a video of how to modify it, what application is required to open it
?

**Comment by FalloutNVFanGene** [comment]
Okay, I did some looking into it, every time I changed the file, it made a BAK file, And the BAK file did not change, so I had to edit the BAK file, and delete the other BAK files, I have it all working now.
