### ISSUE TITLE
[Compatibility]Smiths trying to Heal Extra Golems Mod's Golems

### ISSUE THREAD

**Issue by Nin-10-doer** [seymourimadeit/guardvillagers#55]
So I just installed a bunch of villages focused mods and one day I started to hear a loud sound like something was bugged, so just found a villager trying to heal a mushroom golem from extra golems mod, the golem was already at 100% but the Villager kept healing it so this led to this infinite healing sound effect playing over and over until it was work time and the villager went to his workstation.

**Comment by BugmanBugman** [comment]
I can confirm this as well

**Comment by skyjay1** [comment]
This is an issue with Guard Villagers, see [this issue](https://github.com/MinecraftModDevelopmentMods/Extra-Golems/issues/65) for more information
