### ISSUE TITLE
(Incompatibility) Ticking Entity Crashes

### ISSUE THREAD

**Issue by Coraline77447** [seymourimadeit/guardvillagers#57]
Hi, I'm experiencing some incompatibilities with this mod and Scaling Health mod which causes the guard villagers to become ticking entities whenever scaling health mod is installed and getting too close to a village both vanilla and modded from Repurposed Structures mod. Btw my minecraft java edition version is 1.16.4, forge version is 35.1.28, mods versions for both of them are: Guard Villagers 1.1.8, Scaling Health 4.0.1 +1. So can you please make both this mod and scaling health mod compatible? (Btw I am going to report this same thing to scaling health mod so that if they agree with the compatibility agreement for both this mod and scaling health mod to be compatible with each other without ticking entities (btw when the guard villagers becomes ticking entities I would kill them via kill command (/kill @e[type=guardvillagers]) which I don't like doing that to the guard villagers but it's either them or me...

**Comment by seymourimadeit** [comment]
Please give a crash report, and some logs too.

**Comment by Coraline77447** [comment]
Here's the latest crash report and the log (not the latest log tho but its the one with the ticking entities) before Coraline World 2 1.16.4 (Modded) was deleted in anger and frustration from the ticking entities before making a new world with the same name. Btw the ticking entity crash happened on my new modded survival world when I found a dark forest village (a copy of a plains village by Repurposed Structures mod) so I uninstalled Scaling Health and kept the guard villagers installed which the guard villagers aren't ticking entities without scaling health but with that mod then yes they are ticking entities; 

Crash Report: [crash-2021-01-02_06.46.20-server.txt](https://github.com/seymourimadeit/guardvillagers/files/5761219/crash-2021-01-02_06.46.20-server.txt)

Log: [2021-01-02-11.log](https://github.com/seymourimadeit/guardvillagers/files/5761228/2021-01-02-11.log)

**Comment by seymourimadeit** [comment]
A mod called Lost Trinkets seems to be causing this, not guard villagers. The guard villagers mod isn't even mentioned once in that crash report except in the mod list.

**Comment by Coraline77447** [comment]
Then why is Lost Trinkets causing your guard villagers to become ticking entities? Now I'm really confused to what's really going on between this mod, scaling health and lost trinkets and really need some help since I'm no modder and that I don't exactly understand both crash reports and logs when something goes wrong during my modded play sessions cause I'm guessing that something is going on between lost trinkets and scaling health. 

Also when I'd /kill @e[type=guardvillagers:guard] all of the guards on my last modded world before I deleted it that I didn't crash from ticking entities within the villages I've discovered already up till I crashed again by the same problem within the same swamp village that was close by to the one I'd built which didn't have any guard villagers cause I killed them all, thought that I'd killed them all but now I'm thinkin that I have killed them all but why the crash happened again was probably cause of lost trinkets mod doesn't like scaling health mod...

Lost Trinkets probably won't like First Aid mod either since First Aid completely changes the player's health system entirely with a new one and some of the trinkets in Lost Trinkets probably fiddles around with the health system as of the vanilla one and hates other mods that alters the vanilla health system... 

So I probably shouldn't have lost trinkets with any health mods together since that combo causes ticking entities... Btw sorry for this reply being an essay to read but I'm just telling you my thoughts about this situation that I'm going through with these mods....
