### ISSUE TITLE
[Suggestion] Additional functionality with armor stand and guard villagers.

### ISSUE THREAD

**Issue by Marteori** [seymourimadeit/guardvillagers#58]
- Guard villagers can take armor from the armor stand.
- If they have armor on them, they change their armor on the armor stand, if they are better.
- And add some requirement for the armor stand at which they will be able to take armor. (For example, that the armorstand stood on a block of andesite) [Otherwise they will be able to remove armor that stands for decoration]

P.S. _My english is not a good, if something unclear ask me I try to answer in a different way._

**Comment by jengendler** [comment]
I like this idea. It would be even cooler if armor stands are actually guard workstation blocks, that way if a guard dies, their workstation becomes free, allowing a villager without a profession to take up a guard post. I can imagine making barracks using these functional guard armor stands! Perhaps don’t override vanilla armor stands, but create a special guard one for the mod. There may need to be a way to lock in a guard’s profession (just like trading with a villager does) if this workstation mechanic is added.

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
