### ISSUE TITLE
Whenever a guard follows a player on a server, it crashes the server by using a singleplayer only function.

### ISSUE THREAD

**Issue by queenbiscuit311** [seymourimadeit/guardvillagers#58]
Is this a bug, or does this mod just not work on servers? I'm on 1.17.1.

[crash log](https://pastebin.com/z18iEq32)

I know it's related to this mod because it only happens when someone has hero of the village.

**Comment by seymourimadeit** [comment]
This crash seems to be more of an issue with the Netherite Hammer item from "Stalwarts Dungeons" using a client only function than guardvillagers.
