### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by FurryApocalypse** [seymourimadeit/guardvillagers#6]
Hi there.
I have already played with guard villagers on server with mods like ice and fire and champions.
My sugestion is to add some stronger guards, some sort of ranks or ways to improve strenght of your villager.

I could just suggest to add guards to champions mod so guards would have affixes and scallings  but i think this could ruin the way guard villagers works now (imagine guard with magnetics or with poison aura in village... ouch) 

So thats my suggestion ^^

**Comment by seymourimadeit** [comment]
Read the pinned post before posting any issues. NO SUGGESTIONS ARE ALLOWED ON THIS ISSUE PAGE, POST THEM ON THE DISCORD OR ON THE OTHER PAGE I LINKED IN THE PINNED POST.
