### ISSUE TITLE
Server Crash w/ Config

### ISSUE THREAD

**Issue by WenXin20** [seymourimadeit/guardvillagers#6]
Minecraft v1.15.2
Forge v31.2.19
Villager Guards v1.0.7

My server crashes due to a config error. Nothing in the config was changed. 
The crash seems to be related to the last line in the config file that says `= true`. If I add `"Have guards avoid friendly fire? This is experimental"` in front of the `= true`, the server will no longer crash.

[Crash Report](https://gist.github.com/WenXin20/8999714486218d272a2f52019886a75e)

**Comment by seymourimadeit** [comment]
delete your config, and re-download the mod
