### ISSUE TITLE
Broken with Radium Reforged (Forge port of Lithium)

### ISSUE THREAD

**Issue by brisingraerowing** [seymourimadeit/guardvillagers#61]
[Crash Log](https://gist.github.com/BrisingrAerowing/312a18dd1b088c4ab8a4c4b4f4686ffe)

Botania had a similar issue, fixed [in this commit](https://github.com/VazkiiMods/Botania/commit/5dc3379a115818f177643fbce6899a492241b10c).

**Comment by seymourimadeit** [comment]
this is gonna have to be marked as wont-fix as hundreds of other mods use events like mines that add ai to other mobs, i think this problem is gonna have to brought up with the radium devs themselves
