### ISSUE TITLE
Guards are not spawning when starting a new map

### ISSUE THREAD

**Issue by FrannDzs** [seymourimadeit/guardvillagers#62]
Hello! Good afternoon. That, I have some mods installed but I cannot find the error or which mod is interfering, the console does not show anything, is there any way to see if the entities are loaded but they are invisible? I also want to clarify that if I press shift + right click a villager if they become guards, but do not spawn at startup. I would like an orientation please. I can provide the log but it doesn't show anything. I remember seeing a No data fixer registered for Guard

**Comment by abigailfails** [comment]
There isn't much information here but from what I can guess the guards didn't spawn because another mod or datapack was also overriding `iron_golem.nbt`. If this was the problem, it was fixed in 9ce9b0a. If it still happens after the GV's next release feel free to repoen the issue.
