### ISSUE TITLE
multi layered helmets are not fitting on the guard's big head...

### ISSUE THREAD

**Issue by bokomix** [seymourimadeit/guardvillagers#63]
so I'm using a resource pack where helmets have a second layer on them for more details...
anyways it seems that the guard's heads are too big for them and the second layer of the helmets render weirdly as if they are suposed to use a regular Steve head, but I want to use the villager model. could you please fix that? :3 and thanks
![2022-01-24_21 14 48](https://user-images.githubusercontent.com/98351159/150849012-0b73a48f-52fb-4db9-9842-4e0a4cae98c3.png)
![2022-01-24_21 15 00](https://user-images.githubusercontent.com/98351159/150849022-f8901342-081f-4e35-a8de-fa765cdc18ef.png)

**Comment by seymourimadeit** [comment]
I'm gonna mark this as wontfix for simply two reasons
1. This problem will probably occur with any mob with a villager head 
2. This might be fixable by making an alternative texture just for guards and other villager mobs, but checking every resource pack and asking them to make a single texture for the helmet just for that seems ridiculous
