### ISSUE TITLE
Village Guard Config

### ISSUE THREAD

**Issue by ElCow-cyber** [seymourimadeit/guardvillagers#63]
So I set the "AttackAllMobs" to true but how can I add the creeper to the blacklist? please help

**Comment by seymourimadeit** [comment]
![75dtzTv](https://user-images.githubusercontent.com/55965249/104332534-21e62500-54a5-11eb-8f5e-3359eedec8c0.png)

**Comment by ElCow-cyber** [comment]
Thankyou so much 👍
