### ISSUE TITLE
Request: Bed for guards

### ISSUE THREAD

**Issue by kihgy** [seymourimadeit/guardvillagers#64]
I would like to have guards to claim beds like normal villagers, when the bed is claimed, the guard will patrol a nearby area around it, not stray to far, and will return at day to heal. Without bed, guards will wander off the village.

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
