### ISSUE TITLE
Some AI issues

### ISSUE THREAD

**Issue by Atlantispy** [seymourimadeit/guardvillagers#64]
-Often multiple guards attack the same creature, but line up behind each other to shoot, causing unnecessary damage.
-They seem to stand while reloading and get hit rather than back off. Could the AI from Big Brain pillagers be applied to them for this?

**Comment by seymourimadeit** [comment]
1. If you don't want this to happen activate the friendly fire options in the config
2. I probably won't use the same pillager ai I added in Big Brain simply because I don't want them to feel the same
