### ISSUE TITLE
Suggestion: Configurable Guard Stats/ Issue with Guard Awareness Range

### ISSUE THREAD

**Issue by CapitaineYolo** [seymourimadeit/guardvillagers#65]
Hey, I enjoy this mod a lot and am trying to design good defensive vantage points fior the guards. 

![2022-02-06_20 06 45](https://user-images.githubusercontent.com/75442607/152697382-c8d99f42-13bb-4f3d-9e72-38553d3976be.png)

So far it seems that Guards don't notice mobs approaching on the ground most of the time and they are also quite inaccurate. I wish I could change their stats, especially their awareness range, their crossbows range and accuracy. It would also be a good thing if toolsmiths could repair the guards equipment.

**Comment by CapitaineYolo** [comment]
Reloadspeed and Health would be other great Stats to modify!

**Comment by seymourimadeit** [comment]
#3
