### ISSUE TITLE
[{Feature Request} 1.16] Add a new varient of the Iron Golem, "Ranged Golem".

### ISSUE THREAD

**Issue by mettlephaontoms** [seymourimadeit/guardvillagers#65]
Ive been looking for Forge mods that expand on the iron golems and ive only found one other mod that messes with their combat slightly, it would be awesome to see ranged golems in this mod. Perhaps the iron golems have specialized redstone dispensers implanted in their arms, or their eyes are capable of producing harmful lasers with a model or models unlike the guardians laser.

Fletchers can provide ammunition to these ranged golems if they use arrows, maybe even tipped arrows and rockets.

**Comment by seymourimadeit** [comment]
New golems will not be added to this mod.
