### ISSUE TITLE
"Registry remapping failed: Received ID map for minecraft:entity_type constains IDs unknown to the receiver!"

### ISSUE THREAD

**Issue by AwwItsCookie** [seymourimadeit/guardvillagers#66]
So uh I was watching recently a streamer that played minecraft with a modpack on curseforge, which I installed on same version same everything... now the mod works perfectly but when I try to join the server they're in it gives me the error in the title associated with this: "- guardvillagers:guard" so I searched the mod found this and started the issue.

It only occurs when I join the Multiplayer server which is run by a number ip address thing, don't know if that has anything to do with it but I don't really think so.

I did change the RAM to 8G so it can run smoother, but other than that I believe I did nothing else.

Please help, I wanna join this server but am unable to no matter what I try.

**Comment by AwwItsCookie** [comment]
I'll try deleting it and reinstalling it (By the way I didn't mention this in the issue but, the version of the modpack is v13 and it's 1.18.1)

**Comment by seymourimadeit** [comment]
Please send your latest.log file

**Comment by AwwItsCookie** [comment]
I uh I got to fix it, sorry I didn't say this earlier

I only had to uninstall the v14.5 and the v13 in curseforge app then reinstall it but with the v13 version only

Thanks tho
