### ISSUE TITLE
Compatibility and feature request

### ISSUE THREAD

**Issue by Appalachianginger** [seymourimadeit/guardvillagers#68]
To start with I absolutely love this mod and think that you are doing a fantastic job with it. You should be very proud of the work you've done

There are some compatibility issues with Spartan weaponry. All melee and shields work with the guards but the crossbows do not. I believe it's because the Spartan crossbows use bolts instead of arrows.

When playing in survival I made a wall to defend the village and wanted to have the guard villagers stationed on the wall to shoot at attackers but they wonder around. It would be nice if there was a way to make the archers stand still and the swordsman guard a certain area.

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
