### ISSUE TITLE
Patrol button not working at all

### ISSUE THREAD

**Issue by BeanCan112** [seymourimadeit/guardvillagers#68]
When I click the button for the guards to patrol that area they still continue walking around. The follow button works perfectly fine but for some reason not the patrol button.

**Comment by seymourimadeit** [comment]
Please send a video recording of this. Keep in mind that when guards with melee items are set to patrol an area they should walk back and forth around that area.

**Comment by BeanCan112** [comment]
> Please send a video recording of this. Keep in mind that when guards with melee items are set to patrol an area they should walk back and forth around that area.

Cant currently as i am do not have access to my PC but will be able to either tomorrow or day after. Thanks

**Comment by Leothedemon** [comment]
Yeah im having the same problem too

**Comment by seymourimadeit** [comment]
> > Please send a video recording of this. Keep in mind that when guards with melee items are set to patrol an area they should walk back and forth around that area.
> 
> Cant currently as i am do not have access to my PC but will be able to either tomorrow or day after. Thanks

Are there any updates on this?

**Comment by seymourimadeit** [comment]
I'm gonna have to close this due to inactivity, I will reopen this if any further updates come.
