### ISSUE TITLE
some suggestions of grands and villagers's feature

### ISSUE THREAD

**Issue by bucketBrian** [seymourimadeit/guardvillagers#7]
- bow grands, or AKA _Snipers_
I think the grands should use bows and have some differences between crossbowmen.
I'd like to call them the "sniper", compared to the crossbowman, sniper grands have a much larger range(at least 32 blocks) and cause larger damage. but they can't knockback the attacker and are not as agile as crossbowmen.
 
- be poised for launch!
crossbow grands should load an arrow when idle, that they can shoot immediately when attacking.
 
- advanced Clerics
I think it was reasonable to let the high-rank clerics use the potions of strong regeneration or potions of healing (it they can use it I think it was a good idea to let clerics use it to fight back zombies)

**Comment by seymourimadeit** [comment]
This suggestion is still being kept in mind, but all feature requests must be posted on either the discord or this repo https://github.com/seymourimadeit/guardvillager-suggestions/issues
