### ISSUE TITLE
Villagers go poof

### ISSUE THREAD

**Issue by MisterFIG1** [seymourimadeit/guardvillagers#7]
Hey there, trying out your mod. I have a java 1.16.5 server with the forge mod added. I also added the guardvillagers but something strong occurs.
If type in the command to give myself or someone a guard spawn egg, I receive the egg, right click it, but nothing happens. Likewise, when I right shift click on a nitwit or unemployed villager, with a sword, the sword and the villager seem to vanish. 
I have the guardvillager mod in the mod folder, the latest version of the mod in fact.
Any suggestions?

**Comment by seymourimadeit** [comment]
Send the debug.log and latest.log file. The current list of mods you have would also help too

**Comment by MisterFIG1** [comment]
Howdy. Sorry it took so long, here are the two most recent logs. See
attached.
The only plugins I have are
guardvillagers 1.16.5.1.24
OhtheDungeon
Ultimate Timber 2.2.4

I don't have any debug logs alas, or least none I could identify

Hope this helps. I will see what else I can dig up if need be. I appreciate
any input you have!

**Comment by seymourimadeit** [comment]
There are no logs as far as I can see in your post, try putting them on pastebin.

**Comment by MisterFIG1** [comment]
[2021-04-23-1.log.gz](https://github.com/seymourimadeit/guardvillagers/files/6373643/2021-04-23-1.log.gz)
[2021-04-24-1.log.gz](https://github.com/seymourimadeit/guardvillagers/files/6373645/2021-04-24-1.log.gz)

**Comment by MisterFIG1** [comment]
Sorry about that. I am also using the latest version of Forge

**Comment by seymourimadeit** [comment]
Recreate the bug and send another log file (eg, typing /summon guardvillagers:guard), there seems to be nothing related to the bug your stating in the files you sent.

**Comment by MisterFIG1** [comment]
okay I will try it now

**Comment by MisterFIG1** [comment]
[latest.log](https://github.com/seymourimadeit/guardvillagers/files/6373697/latest.log)

**Comment by seymourimadeit** [comment]
The log says that you have the guardvillagers jar file in the plugins folder, trying removing that out and put it in the mods folder if it isn't already.

**Comment by MisterFIG1** [comment]
Ok I removed it from the plugins folder, and put it in the mods folder.
I started the server back up and did /summon  guardvillagers:guard
It said "unknown entity: guardvillagers:guard"

**Comment by seymourimadeit** [comment]
Could you see if you have the mod actually loaded by checking the mod list in the main menu?

**Comment by MisterFIG1** [comment]
Yes, I checked. It shows guardvillagers as a mod installed on the main menu of the minecraft launcher.

**Comment by seymourimadeit** [comment]
Could you send me your logs again?

**Comment by MisterFIG1** [comment]
Righto, I will send the most recent one yet.

**Comment by MisterFIG1** [comment]
[2021-04-25-1.log.gz](https://github.com/seymourimadeit/guardvillagers/files/6373935/2021-04-25-1.log.gz)

**Comment by seymourimadeit** [comment]
That appears to be the same log as the last one you sent me, could you send the latest.log file if it's not the same as that?

**Comment by MisterFIG1** [comment]
sorry, I will try again

**Comment by MisterFIG1** [comment]
[latest.log](https://github.com/seymourimadeit/guardvillagers/files/6374016/latest.log)
Im sure its something silly that I forgot to do. I am using a paper server, if that helps.

**Comment by seymourimadeit** [comment]
It seems like paper servers don't support forge mods. 
https://paper.readthedocs.io/en/latest/about/faq.html

**Comment by MisterFIG1** [comment]
Well darn, thats a bummer
