### ISSUE TITLE
Some of the village guards are trying to kill me.

### ISSUE THREAD

**Issue by Stoya4** [seymourimadeit/guardvillagers#70]
Hello, there is a problem with the "Guard Villagers" mod, when approaching any village one of the guards attacks, usually it's one, well, or a maximum of two, the rest are completely neutral like an iron golem, increasing reputation does not give any result, I tried to clear the world cache but the situation has not changed, only getting the status "Hero of the village" helps, but as soon as the effect disappears and I move away from the village further than ~500 blocks, random 1-2 guards again try to kill me.

**Comment by seymourimadeit** [comment]
If you have a mod like ai improvements try removing them.
