### ISSUE TITLE
Server Crashes When I try to access guard inventory 

### ISSUE THREAD

**Issue by AmitShergill** [seymourimadeit/guardvillagers#71]
I have my settings set to false for accessing a guards inventory only with the hero of the village effect, and also for false for stationing a guard with the hero of the village effect, but every time I right click a guard, my server crashes

**Comment by seymourimadeit** [comment]
Please send the full crash report .txt file.

**Comment by AmitShergill** [comment]
![Uploading B092E27F-1246-4B85-8CB2-3A2D79A32291.jpeg…]()

**Comment by AmitShergill** [comment]
![FFF11AA2-A893-4D84-A744-E1BB3FA438EF](https://user-images.githubusercontent.com/103163007/162337330-fd17346e-e67d-44d3-a545-93d1c69138b0.jpeg)
![0D2C4144-C539-4B4E-9A12-10E01E8E423C](https://user-images.githubusercontent.com/103163007/162337333-5ad79403-6219-4fd9-8d72-3d63284d6836.jpeg)
![8AF3B533-9C0D-4475-BB8B-32D01F35B550](https://user-images.githubusercontent.com/103163007/162337336-90424677-f41a-4f07-9b0c-a1ff3d9b0454.jpeg)

**Comment by AmitShergill** [comment]
> 

Sent

**Comment by seymourimadeit** [comment]
Please don't send an image, send the .txt file or the latest.log file. The image doesn't show the full crash report that well.

**Comment by AmitShergill** [comment]
https://mclo.gs/VFr1Qw6

**Comment by AmitShergill** [comment]
is that better?

**Comment by seymourimadeit** [comment]
> is that better?

Yes



> https://mclo.gs/VFr1Qw6

Something from bukkit is messing up the mod. If I'm gonna be honest here I probably won't be able to do anything about this, please take this to the devs of bukkit itself.
