### ISSUE TITLE
Guard Villagers Crash - 1.18.2 Fabric - Inside of an Unfinished Modpack

### ISSUE THREAD

**Issue by CYNO-MC** [seymourimadeit/guardvillagers#72]
Before the crash, I had just loaded into a creative world to test the modpack itself. I spawned around 10-15 at a pillager camp, and flew off in the other direction. shortly after, my game crashed and this was the error I received.

[crash-2022-04-14_09.07.17-server.txt](https://github.com/seymourimadeit/guardvillagers/files/8489385/crash-2022-04-14_09.07.17-server.txt)

**Comment by FlameyFaucet** [comment]
this is the fabric version it seems, you should ask them instead, i believe they have a discord server

**Comment by seymourimadeit** [comment]
Please report this to the fabric version's github or discord server 

https://www.curseforge.com/minecraft/mc-mods/guard-villagers-fabric
