### ISSUE TITLE
(question) How do I correctly configure Guard mobs Black List?

### ISSUE THREAD

**Issue by Brun333rp** [seymourimadeit/guardvillagers#73]
Do I have to separate subjects with commas? Or each of them need to be separated inside brackets?

example: "[minecraft:creeper, minecraft:enderman]" or "[minecraft:creeper] [minecraft:enderman]" ?

**Comment by seymourimadeit** [comment]
Please go into the discord to ask questions, not here.

**Comment by Brun333rp** [comment]
ok, sorry
