### ISSUE TITLE
Making a guard villager crashes the game

### ISSUE THREAD

**Issue by nicky-chin** [seymourimadeit/guardvillagers#74]
Hi I'm playing on a Minehut server on 1.18.2 and every time I try and make a guard villager the game crashes. This is the crash report
[crash-2022-04-19_18.14.52-client.txt](https://github.com/seymourimadeit/guardvillagers/files/8517172/crash-2022-04-19_18.14.52-client.txt)

**Comment by seymourimadeit** [comment]
Judging by the crash report it seems like you're playing the fabric version, which I do not develop, please go here for fabric support.
