### ISSUE TITLE
Guard Villagers consuming a lot of server tick time.

### ISSUE THREAD

**Issue by SpeedSlider** [seymourimadeit/guardvillagers#75]
We have setup a community server with a modpack that includes the guard villager mod and they seem to take up at least half of the server tick time. I have attach a spark profile that a server host requested that I run for some player connection issues. I am not saying the mod is preventing the players from connecting I was just surprised out how much resources were used by guard villager entities. I have pasted the specific line below as well as a link to the Spark profile. I was wondering if there we some changes that I could make in the config that would help.

net.minecraft.world.World.guardEntityTick()53.14% (The percentage is how much of the server thread tick time is allotted to the task)

https://spark.lucko.me/QZ7q3JrdGk

**Comment by seymourimadeit** [comment]
That's just a method minecraft uses, not a guardvillagers thing.
