### ISSUE TITLE
Enhancement request: repairing Golems, armor, & weapons, healing Guards, and Hero

### ISSUE THREAD

**Issue by soulhakr** [seymourimadeit/guardvillagers#75]
- allow armorsmiths repair the iron plate and chainmail armor on Guards and the Hero of the Village (maybe allow them to repair other modded metal armor in the config)
- allow leatherworkers repair leather armor on Guards and Hero of the Village
- allow weaponsmiths repair swords, axes, and shields 
- allow Guards to be equipped with splash potions they can throw
- how about a special village structure called the Barracks?

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
