### ISSUE TITLE
[1.16.4] change to config file crashing on startup

### ISSUE THREAD

**Issue by Zygus42** [seymourimadeit/guardvillagers#76]
I made some changes to the settings in the config file, and it crashes on startup because of it.  Perhaps I got some syntax wrong ?  Perhaps in the Mob Blacklist section ?  Any help would be appreciated.

[guardvillagers-common.toml.txt](https://github.com/seymourimadeit/guardvillagers/files/5917620/guardvillagers-common.toml.txt)

(Changed to txt file to allow import into here)

**Comment by seymourimadeit** [comment]
put minecraft:creeper in quotations in the blacklist.
