### ISSUE TITLE
guard villager with "improved mobs" mod make villager a free enchanting machine

### ISSUE THREAD

**Issue by rtxyd** [seymourimadeit/guardvillagers#78]
When the difficulty of "improved mobs" come to a high number, when you give a villager any weapon, this item has a high chance to be enchanted,  Then kill the guard can take the item back, repeat the operation can be a disaster.
  If there is a chance to keep the nbt data of the item player give, could be better to give compat to other mods.

**Comment by seymourimadeit** [comment]
Improved Mobs should have a black list to mitigate against this. 


EDIT: upon some further investigation I found out they don't unless I missed something, please go suggest this to the creator of that mod.
