### ISSUE TITLE
Found a small, odd incompatibility with minecolonies (1.16.5)

### ISSUE THREAD

**Issue by Luxenmatori** [seymourimadeit/guardvillagers#79]
I read the rules but if this shouldn't be here, please let me know.

There is a weird issue between this mod and minecolonies. For some reason, guards attack farmers from Minecolonies. ONLY THE FARMERS. Even if "attack all mobs" is disabled and they're added to the blacklist. They don't bother any other citizen type from Minecolonies. This is odd because the citizen entity is similar to vanilla villagers: there's only one entity that can change jobs. However something about  causes the guards to aggro on them

I've tested with creepers and endermen and can confirm the blacklist is working properly but they still hate the farmers for some reason.

This isn't game breaking but if a farmer manages to wander too close to a village or a guard, every guard in the area aggros on them.

**Comment by seymourimadeit** [comment]
Could you see if this affects the 1.18 versions? I don't support 1.16.5 anymore for my mods.

**Comment by Luxenmatori** [comment]
Took a while to test it but it seems the guards work as intended on 1.18.2.

It is sad that older versions are no longer supported but with that said: as someone who has very minimal coding experience, what resources could i use to figure out how to make a patch for 1.16? (assuming that's okay with you)

**Comment by seymourimadeit** [comment]
> what resources could i use to figure out how to make a patch for 1.16? (assuming that's okay with you)

Honestly the best resource would be to learn java, and if you are successful in making a patch you're more than welcome to submit it as a pr to this repo, just don't make a modified .jar file because I'd rather not have 50 different .jar files going around for this single mod.
