### ISSUE TITLE
Can't open guard villager's inventory

### ISSUE THREAD

**Issue by Sublimehurdle** [seymourimadeit/guardvillagers#8]
I am in creative mode and I can't open their inventory by right click after recruited them.

**Comment by DaLumma** [comment]
do you have hero of the village?

**Comment by Sublimehurdle** [comment]
So is there an option that can open guard villager's inventory without the effect ?

**Comment by DaLumma** [comment]
there is a config, but even if you set that to true they won't have the button to follow you. but you can give them armor and set them to patrol
