### ISSUE TITLE
Mod crashes on the newest release

### ISSUE THREAD

**Issue by SkullHunter55** [seymourimadeit/guardvillagers#80]
[crash-2021-02-10_06.36.44-server.txt](https://github.com/seymourimadeit/guardvillagers/files/5956065/crash-2021-02-10_06.36.44-server.txt)

**Comment by seymourimadeit** [comment]
have you tried redownloading the mod? i released a hotfix that should patch this

**Comment by seymourimadeit** [comment]
Closing this as this should be fixed due to the latest hot fix, if anyone else still gets this problem even after redownloading the mod, I will reopen this.
