### ISSUE TITLE
Crash when use mob blackList

### ISSUE THREAD

**Issue by Fiocher** [seymourimadeit/guardvillagers#81]
![Snipaste_2022-05-16_12-02-28](https://user-images.githubusercontent.com/82749343/168518082-6abd2b24-dba9-44fe-9ad6-aea4ef37a08f.png)
[crash-2022-05-16_12.02.52-client.txt](https://github.com/seymourimadeit/guardvillagers/files/8697075/crash-2022-05-16_12.02.52-client.txt)

Is there a format error?

**Comment by seymourimadeit** [comment]
put the mob id in quotation marks
