### ISSUE TITLE
[1.16.5] Guards not spawning in Modded Village types anymore as of latest update

### ISSUE THREAD

**Issue by NJL5390** [seymourimadeit/guardvillagers#81]
Minecraft Version: 1.16.5
Forge Version: 36.0.22
Guard Villagers version: 1.1.9

I noticed that after using the latest version of the mod (1.1.9) and generating some test worlds that Guards will now no longer spawn in modded village types like they used to prior to this update and instead only seem to generate in vanilla villages. I'm not sure if this was intentional or not so I'm reporting it here in case it's not.

Here's some screenshots to shown what I mean:

This was taken at a Mountain village from Repurposed Structures (No guards can be seen):
![2021-02-12_23 46 33](https://user-images.githubusercontent.com/64381954/107834568-5db72780-6d8e-11eb-8a35-39e95ee50834.png)

However, This one was taken at a Vanilla Snowy Village (Guards can be clearly seen):
![2021-02-12_23 47 11](https://user-images.githubusercontent.com/64381954/107834620-8f2ff300-6d8e-11eb-9ab9-407782abdc86.png)

Here's my latest log: https://pastebin.com/QfN02Pcf

(The other mod used as an example in the screenshots was Repurposed Structures version 2.3.4: https://www.curseforge.com/minecraft/mc-mods/repurposed-structures)

**Comment by LeSalux** [comment]
I have the same issue in 1.16.5 with the guards not spawning in a modified village. I am using the WallsOfConquest generation datapack.

**Comment by seymourimadeit** [comment]
This should be fixed in the next update since I reimplemented the mod having a built in datapack that overrides the iron_golem nbt file in village structures. It might not work if you have another datapack that overrides that same file however, but that can be fixed easily.
