### ISSUE TITLE
Unable to Create Guards

### ISSUE THREAD

**Issue by StealthMeister1** [seymourimadeit/guardvillagers#82]
No idea why I can't create guards. I've made sure that they are unemployed. I spawned some of my own and still can't. Went to a village that had a few unemployed villagers, still couldn't. Idk what to do.

**Comment by seymourimadeit** [comment]
Are you crouching and right clicking with a sword or crossbow and directly facing the guards?
If you're doing it correctly and they're still not loading you may have a modified config, if so please check if you have the convert guards to villagers only if you have hero of the village option on and turn it off (note, this is not on by default)

**Comment by StealthMeister1** [comment]
I am crouching and directly facing them. I tried it with and without the hero of the village buff before posting. Nothing works. Idk how to check the config.

**Comment by StealthMeister1** [comment]
I also haven't seen them spawn naturally in villages.

**Comment by seymourimadeit** [comment]
Send your latest.log file after you've recreated this bug.

**Comment by StealthMeister1** [comment]
[latest.log](https://github.com/seymourimadeit/guardvillagers/files/8705355/latest.log)

**Comment by FlameyFaucet** [comment]
it appears you're using the fabric version. they have a separate issue tracker, report this to them instead.
actually, second thought:
i can't seem to find the mod being loaded in the log. do you even..._have it installed?_

**Comment by StealthMeister1** [comment]
Yes

**Comment by StealthMeister1** [comment]
Where am I supposed to report this? Why close it without giving me the information to report it to the correct people? Is this not seymour's mod? I am confused.

**Comment by seymourimadeit** [comment]
I apologize for not giving you the link to the fabric versions page.

Here it is:
https://github.com/mrsterner/GuardVillagers/issues

This github page is for the original forge version, since you're playing the fabric version it is more appropriate to report it to the link above.
