### ISSUE TITLE
Advice for blacksmiths

### ISSUE THREAD

**Issue by 48004800** [seymourimadeit/guardvillagers#82]
Connect the blacksmith's healing effect with the golem's health
In this way, it can be compatible with other mods and can also prevent noise

**Comment by abigailfails** [comment]
Your suggestion is being considered, but would you be able to post it again [here](https://github.com/seymourimadeit/guardvillager-suggestions/issues)? We've decided to move suggestions to their own repository to make it easier to see bugs.
