### ISSUE TITLE
Los guardias no toman las armaduras

### ISSUE THREAD

**Issue by KarlTusken** [seymourimadeit/guardvillagers#86]
Tengo un problema con la versión 1.16.5-1.1.10 que acabo de descargar: Los guardias no toman las armaduras que les lanzó, ni siquiera las miran. Por otro lado tampoco reciben los escudos que les intento dar con Shitf-clic derecho y tampoco les puedo quitar el arma para cambiarselas por otra. ¿Es un error? ¿O que debo hacer para reparar este este problema?

**Comment by seymourimadeit** [comment]
Please put this in english as I don't speak spanish. From what I can tell from google translate you seem to be trying to make the guards gain armor by dropping armor, you are also attempting to give guards a shield by shift right clicking them, these two features have been removed in favor of an inventory gui that can be opened by right clicking the guard if you have hero of the village.

**Comment by KarlTusken** [comment]
Thanks for the info! The update features are not in the description
