### ISSUE TITLE
Cannot change guard villager HP with config

### ISSUE THREAD

**Issue by sharlin073** [seymourimadeit/guardvillagers#87]
Version: Latest
Forge 36.0.22

I changed their HP to be 40, but they still have 20 HP.

It seems like running this mod alone does not solve this issue.
I'm not sure what is causing this.

**Comment by seymourimadeit** [comment]
fixed in dev

**Comment by sharlin073** [comment]
Thanks! Could you let me know rough insights on when it will be available, please? (Or, if there's a way to download another version please let me know... I'm really not familiar with this environment.

Either way, thanks a lot!
