### ISSUE TITLE
Loot table issues

### ISSUE THREAD

**Issue by pjlasl** [seymourimadeit/guardvillagers#88]
[ERROR] .... [co.te.bl.Blame/]:

****************** Blame Report 1.9.2 ******************

Found a Loot Table path that does not exist: guardvillagers:entity/guard_legs
The path represented by this Loot Table is: data/guardvillagers/loot_tables/entity/guard_legs.json
Loot Table method called at: tallestegg.guardvillagers.entities.GuardEntity.getItemsFromLootTable
tallestegg.guardvillagers.entities.GuardEntity.func_180481_a
Most common cause is that the Loot Table file is not actually at that location.
Please let the mod author know about this so they can check to see if their Loot Table is correct.

[ERROR] .... [co.te.bl.Blame/]:
****************** Blame Report 1.9.2 ******************
Found a Loot Table path that does not exist: guardvillagers:entity/guard_chestplate
The path represented by this Loot Table is: data/guardvillagers/loot_tables/entity/guard_chestplate.json
Loot Table method called at: tallestegg.guardvillagers.entities.GuardEntity.getItemsFromLootTable
tallestegg.guardvillagers.entities.GuardEntity.func_180481_a
Most common cause is that the Loot Table file is not actually at that location.
Please let the mod author know about this so they can check to see if their Loot Table is correct.

**Comment by seymourimadeit** [comment]
Fixed already in dev.
