### ISSUE TITLE
Once they start attacking a player, they never stop

### ISSUE THREAD

**Issue by IndolentKheper** [seymourimadeit/guardvillagers#89]
There seriously needs to be an option in the config to block them from attacking players. I accidentally hit a villager who got in the way with a pickaxe (didn't even kill it), all nearby guard villagers who saw it now won't stop attacking unless I kill them. Even with gamerule forgivedeadplayers set to true, they immediately attack the player after respawning. Nothing stops them being hostile, not going far away for a while, or going to another dimension, or logging out, they still attack on sight immediately and if you fight back and other non-hostile guards see it, they'll join in.

At the very least they should obey the forgivedeadplayers gamerule, but that aside, it spoils the fun of the mod when accidental friendly-fire toward villagers or guards can lead to you being forced to exterminate all of them.

Edit: Exterminated all aggressive villagers, made a jobless villager into a guard. He was fine for like a minute, then started attacking me, and I hadn't done anything during that time. So yeah, something buggy with them once any of the villagers in a village start attacking a player. Desperately need a config option to disable being hostile to players.

**Comment by seymourimadeit** [comment]
This is due to your village reputation being low. For now you have to try upping your village reputation via trading and other things without the guards presence. 

A config option for the reputation value used for determining if a guard should attack a player will be added in the near future.
