### ISSUE TITLE
Guards Not Running From Ravagers on Low Health 

### ISSUE THREAD

**Issue by ChrisLTheNerd** [seymourimadeit/guardvillagers#89]
Every time a guard villager is low on health they keep fighting ravager instead of running away. The mod version I'm using guardvillagers-1.16.4-1.1.10. Also I've tried it without any other mods except for Guard Villagers and the issue is still there.
![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/50182206/111016553-9db4fe80-837c-11eb-866e-8ea467885a6b.gif)

**Comment by seymourimadeit** [comment]
That feature is probably gonna be removed in the next update.
