### ISSUE TITLE
1.16.5: Guards do not show up on map in Journeymap.

### ISSUE THREAD

**Issue by Ozzuneoj** [seymourimadeit/guardvillagers#9]
We have a few mods that add mobs to our private server but the guard villagers are the only ones that do not show up at all in Journeymap.

It isn't that they are missing a custom icon, it's that they simply have no marker on the map. There appears to be something different with the way the guard villagers are categorized versus other entities in the game, or other mods.

Villagers, enemy mobs and players all show up. In past versions of Journeymap I don't recall ever seeing mobs that didn't show up at all.

This is using guardvillagers-1.16.5.1.2.4, Forge 36.1.0 and Journeymap 1.16.5-5.7.1.

**Comment by seymourimadeit** [comment]
This is most likely a problem with journey map itself, if it isn't, I will re-open this issue.

Edit : accidently put with instead of this
