### ISSUE TITLE
Error? 1.16

### ISSUE THREAD

**Issue by SukautoX** [seymourimadeit/guardvillagers#9]
when I turn a villager into a guard it turns into a pig.. hehe need help I love ur mod <3

**Comment by seymourimadeit** [comment]
could you send a video of this, and also what forge version your using?

**Comment by SukautoX** [comment]
> could you send a video of this, and also what forge version your using?

Forge
 1.16.1 (32.0.47)

![Minecraft 2020 07 04 - 14 25 53 01](https://user-images.githubusercontent.com/67806851/86506568-079b0280-be03-11ea-817c-c9f324286c54.gif)

**Comment by seymourimadeit** [comment]
try re downloading the mod

**Comment by abigailfails** [comment]
We haven't been able to reproduce this issue yet and I suspect it's an incompatibility with another mod that does something weird with entity creation, making it fail for the guard and spawn a pig instead. I'm closing this for now, but if you encounter the problem again feel free to reopen the issue. Sending a log would be helpful if this happens.
