### ISSUE TITLE
Loot Table Errors in Logs

### ISSUE THREAD

**Issue by mcquestion** [seymourimadeit/guardvillagers#90]
MC Version: 1.16.5
Forge Version: 36.0.55
Mod Version: 1.1.10

latest.log from .minecraft/logs
https://gnomebot.dev/api/guild/file/166630061217153024/231527759279685634/820374859536138280/latest.log

Relevant lines:
[13Mar2021 19:13:37.771] [Render thread/ERROR] [net.minecraft.loot.LootTableManager/]: Couldn't parse loot table guardvillagers:entity/guard_chestplate
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'minecraft:leather_tunic'

[13Mar2021 19:13:37.891] [Render thread/ERROR] [net.minecraft.loot.LootTableManager/]: Couldn't parse loot table guardvillagers:entity/guard_legs
com.google.gson.JsonSyntaxException: Expected name to be an item, was unknown string 'minecraft:leather_pants'

Both the leather chestplate and leggings seem to have incorrect ID's in guard_chestplate.json and guard_legs.json

"minecraft:leather_tunic" should be "minecraft:leather_chestplate"
And
"minecraft:leather_pants" should be "minecraft:leather_leggings"

I was able to fix this by overwriting both .jsons with a datapack, and upon correcting the ID's the log no longer gave out these errors.

PS: Many thanks for the mod! :)

**Comment by seymourimadeit** [comment]
Fixed in dev
