### ISSUE TITLE
Request: Add "whitelist" for guards to attack

### ISSUE THREAD

**Issue by mimi-min** [seymourimadeit/guardvillagers#91]
Hey!

Thanks for this awesome mod, now I don't feel like I have to babysit my villagers constantly!

I love that the guards will also attack hostile modded mobs if it's enabled in the config. 

My issue is, there are some mobs that aren't necessarily hostile, but they are annoying (flies from Alex's Mobs, for example). 

I was wondering if it would be possible to add a list of extra mobs that the guards might be able to attack. I could see this being useful for things like protecting chickens from foxes as well.

Just a thought I had!

Thanks!

**Comment by seymourimadeit** [comment]
#3
