### ISSUE TITLE
Equipment disappears after being struck by lightning

### ISSUE THREAD

**Issue by VaIerka** [seymourimadeit/guardvillagers#92]
When lightning hit guards they turns into witch, but doesn't drop armor they were wearing as well as weapon.

**Comment by seymourimadeit** [comment]
this isn't a bug report and those items would get burnt anyways even if they did drop

**Comment by VaIerka** [comment]
> this isn't a bug report and those items would get burnt anyways even if they did drop

I use item fizic mod. it allows things not to burn that logically don't burn
at all, it's not normal when random lightning destroys a set of diamond armor along with a weapon (yes, I'm that much of a tryharder)
