### ISSUE TITLE
Console crash report spam with The One Probe

### ISSUE THREAD

**Issue by sirben99** [seymourimadeit/guardvillagers#95]
Forge: 36.1.0
Minecraft: 1.16.5
Singeplayer or server:  Both
GuardVillagers mod version: 1.2.0
TheOneProbe version: 3.0.7

Hey!

I noticed that when using The One Probe and GuardVillagers, my console was being spammed with preparing for crash report errors when looking/trying to right click a GuardVillager. Issue has been tested with only GuardVillagers and The One Probe.

Heres the latestl.log: 
[latest.log](https://github.com/seymourimadeit/guardvillagers/files/6203898/latest.log)

**Comment by sirben99** [comment]
McJtyMods/TheOneProbe##452

**Comment by sirben99** [comment]
McJtyMods/TheOneProbe#452

**Comment by seymourimadeit** [comment]
Does the newest update fix this?

**Comment by sirben99** [comment]
> Does the newest update fix this?

Sorry for the late responce. I quit on the computer for today and am going to sleep soon. I will definetöy test tomorrow, but i unfortenatly cant today :/

Ill update you on the situation when ill test it tomorrow!

**Comment by sirben99** [comment]
Hey

I now tested the new version and can say that both server crash and the one probe spam is fixed!

Thank you for the fixes!
