### ISSUE TITLE
Guards can not be clicked

### ISSUE THREAD

**Issue by Avgvstin** [seymourimadeit/guardvillagers#95]
I have this error where newly spawned guards can not be clicked to access their inventory and the ones spawned before experiencing the error can not be put into follow mod.

**Comment by seymourimadeit** [comment]
1. Are these newly spawned guards via a spawn egg?
2. Do you have hero of the village or a high reputation?
3. Make sure you're playing the forge version as the fabric version being made by a separate developer do not have these features

**Comment by Avgvstin** [comment]
Well, i have the forge version for 1.19.2 I tried both 1.5.1 and 1.5.2. I had hero of the village at a certain point. Also, i can access the inventory of the guards spawned before the error but i can't put them in follow mode.The ones spawned via a spawn egg do not work.Also the ones natueally spawned in a village do not work and i can not recruit new ones.

**Comment by Avgvstin** [comment]
As an update it seems now that I can create new guards by clicking villagers with a sword, but their follow option is till missing from their menu.

**Comment by Avgvstin** [comment]
The ones that I spawn with an egg can still not be accessed.

**Comment by seymourimadeit** [comment]
Naturally spawned and spawn egged guards don't give the players access to their inventories immediately. You have to get a high village reputation, have hero of the village, or have them spawn via conversion. You also don't get guards to follow you unless you have hero of the village.

All working as intended.

**Comment by Avgvstin** [comment]
Thank you very much for your help. Keep up the great work.
