### ISSUE TITLE
The guards wont follow

### ISSUE THREAD

**Issue by Temz75** [seymourimadeit/guardvillagers#96]
I set the config to follow even when i don't have hero of the village and they refuse to follow. The patrol button still works but nothing else comes up in their screens.

**Comment by seymourimadeit** [comment]
Can't seem to recreate this. Please send a mod list and logs.

**Comment by Temz75** [comment]
Rex's-AdditionalStructures-1.19.x-(v.4.0.2).jar
<https://drive.google.com/file/d/1HEov2YEmKE3Mx2u7-7z0FhNl2esrYom5/view?usp=drive_web>
 BetterPvPFairPlay_22.14.1_Forge_1.19.1.jar
<https://drive.google.com/file/d/1qJwpw0xhraMKLS06_zbRBrPM7YIb45jR/view?usp=drive_web>
 majruszs-difficulty-1.19.2-1.5.10.jar
<https://drive.google.com/file/d/1N1Wu4VmIXvlMar96jC7l8bssnV0nJR_c/view?usp=drive_web>
 AgeOfWeapons-Reforged-1.19.2-(v.0.7.0).jar
<https://drive.google.com/file/d/1aYf4mqx65v7_3WqIsNnaxH96MuvchE34/view?usp=drive_web>

**Comment by Temz75** [comment]
i cant send the rest cuz it doesn't support file type

**Comment by Temz75** [comment]
okay nevermind i accidentally typed false with 2 "e"s

**Comment by Temz75** [comment]
Okay, so i did manage to have them follow me when i dont have hero of the village, i misstyped false in the config settings. The only issue is that unless i have hero of the village i dont get access to the button to turn the follow feature on or off.

**Comment by seymourimadeit** [comment]
>i have hero of the village i dont get access to the button to turn the follow feature on or off.

Please elaborate on this as it is quite vague. Do you mean you cant access the guard inventory at all or you can't see the button?

**Comment by Temz75** [comment]
I cannot see the button

**Comment by seymourimadeit** [comment]
Is this by any chance happening on a server or on single player?

**Comment by Temz75** [comment]
On a server. I have not tested it in single player

**Comment by seymourimadeit** [comment]
Does the server also have that option enabled?

**Comment by Temz75** [comment]
It does, the villagers still follow when i no longer have hero of the
village. The issue is that once hero of the village is gone i can no longer
see the button

**Comment by seymourimadeit** [comment]
Could you please check if your client also has the option enabled? It could be the reason why the button is not appearing as guis are done on the client side

**Comment by seymourimadeit** [comment]
As it has been 27 days since this issue was last commented on and the original poster has gone inactive I will be closing this. If this issue is still relevant please request to reopen.
