### ISSUE TITLE
Crash with other mod(figured I might as well let it be known)

### ISSUE THREAD

**Issue by KieroVance** [seymourimadeit/guardvillagers#98]
from what I've known this mod has issues with other "ranged" weapons mods, usually, they just can't fire, or similar issues of unusability for the other mod.

but if you give them a gun from the "old guns" mod, it crashes SOON after they attempt to attack.

I don't know if it matters since I don't know if yall attempt to fix those issues(if they can be at all) or if since its another mod you don't/can't do anything about it, but I figured since I've had issues with ranged in the past, might as well put the issue here.

if you want/need anything else added for this, let me know, but its very easily replicatable by giving a guard any gun from the "Old Guns" mod for 1.18.2 version(latest in both forge, and versions of the two mods as I post) it seems to be specifically when they attempt to fire(charges them like a crossbow)

oh, and if somehow you do this on a world you somehow want to keep, a way to save it is to tab out before the world loads, so that it is paused before you are actually started, set it to peaceful so they have nothing to attack, chances are they will still be charging so it will crash anyways, but strangely save the difficulty, once you load it again you can remove the gun from their inventory. tedious, but was worth doing for my world atleast.

that is all I have.

**Comment by seymourimadeit** [comment]
Send a crash report.

**Comment by KieroVance** [comment]
Alright, hopefully I send the right files, if not, let me know.
[crash-2022-11-03_06.11.31-server.txt](https://github.com/seymourimadeit/guardvillagers/files/9927322/crash-2022-11-03_06.11.31-server.txt)
Hopefully that's the correct file, but again, TL;DR: guards with guns from "Old Guns" crash as soon as, what I assume, to be the gun FIRING when they "Charge/Aim" it after a second or so.

**Comment by seymourimadeit** [comment]
https://github.com/zach2039/oldguns/issues/37

When this bug is fixed within the old guns mod (in 1.19) please check again if this bug still happens. I'll be closing this for now.

**Comment by zach2039** [comment]
Crash is fixed in both [v3.6.3-38](https://github.com/zach2039/oldguns/releases/tag/v3.6.3-38) and [v3.7.1-39](https://github.com/zach2039/oldguns/releases/tag/v3.7.1-39) releases of old guns mod, though projectile produced once the villager fires the weapon is just an arrow.

I've got some mixins that allow normal vanilla skeletons to use firearms as a place to start, though that might not be best practice. Some interface for custom weapon behavior might work. Let me know how I can help, if desired.

**Comment by seymourimadeit** [comment]
> Crash is fixed in both [v3.6.3-38](https://github.com/zach2039/oldguns/releases/tag/v3.6.3-38) and [v3.7.1-39](https://github.com/zach2039/oldguns/releases/tag/v3.7.1-39) releases of old guns mod, though projectile produced once the villager fires the weapon is just an arrow.
> 
> I've got some mixins that allow normal vanilla skeletons to use firearms as a place to start, though that might not be best practice. Some interface for custom weapon behavior might work. Let me know how I can help, if desired.

Yes I would like to have a further conversation about compatibility, preferably on discord. My discord is tallestred#1078 if you need it.
